pub struct QueryStat {
    pub database_id: i64,
    pub toplevel: bool,
    pub calls: i64,
}
/// Generated by pco_store to store and load compressed versions of [QueryStat]
pub struct CompressedQueryStats {
    filter: Option<Filter>,
    database_id: i64,
    toplevel: Vec<u8>,
    calls: Vec<u8>,
}
impl CompressedQueryStats {
    /// Loads data for the specified filters.
    pub async fn load(
        db: &impl ::std::ops::Deref<Target = deadpool_postgres::ClientWrapper>,
        mut filter: Filter,
    ) -> anyhow::Result<Vec<CompressedQueryStats>> {
        if filter.database_id.is_empty() {
            return Err(anyhow::Error::msg("database_id".to_string() + " is required"));
        }
        let sql = "SELECT * FROM query_stats WHERE database_id = ANY($1)";
        let mut results = Vec::new();
        for row in db
            .query(&db.prepare_cached(&sql).await?, &[&filter.database_id])
            .await?
        {
            results
                .push(CompressedQueryStats {
                    filter: Some(filter.clone()),
                    database_id: row.get(0usize),
                    toplevel: row.get(1usize),
                    calls: row.get(2usize),
                });
        }
        Ok(results)
    }
    /// Deletes data for the specified filters, returning it to the caller.
    ///
    /// Note that all rows are returned from [decompress][Self::decompress] even if post-decompress filters would normally apply.
    pub async fn delete(
        db: &impl ::std::ops::Deref<Target = deadpool_postgres::ClientWrapper>,
        mut filter: Filter,
    ) -> anyhow::Result<Vec<CompressedQueryStats>> {
        if filter.database_id.is_empty() {
            return Err(anyhow::Error::msg("database_id".to_string() + " is required"));
        }
        let sql = "DELETE FROM query_stats WHERE database_id = ANY($1) RETURNING *";
        let mut results = Vec::new();
        for row in db
            .query(&db.prepare_cached(&sql).await?, &[&filter.database_id])
            .await?
        {
            results
                .push(CompressedQueryStats {
                    filter: None,
                    database_id: row.get(0usize),
                    toplevel: row.get(1usize),
                    calls: row.get(2usize),
                });
        }
        Ok(results)
    }
    /// Decompresses a group of data points.
    pub fn decompress(self) -> anyhow::Result<Vec<QueryStat>> {
        let mut results = Vec::new();
        let toplevel: Vec<u16> = if self.toplevel.is_empty() {
            Vec::new()
        } else {
            ::pco::standalone::simple_decompress(&self.toplevel)?
        };
        let calls: Vec<i64> = if self.calls.is_empty() {
            Vec::new()
        } else {
            ::pco::standalone::simple_decompress(&self.calls)?
        };
        let len = [toplevel.len(), calls.len()].into_iter().max().unwrap_or(0);
        for index in 0..len {
            let row = QueryStat {
                database_id: self.database_id,
                toplevel: toplevel.get(index).cloned().unwrap_or_default() == 1,
                calls: calls.get(index).cloned().unwrap_or_default(),
            };
            if self.filter.as_ref().map(|f| f.filter(&row)) != Some(false) {
                results.push(row);
            }
        }
        Ok(results)
    }
    /// Writes the data to disk.
    pub async fn store(
        db: &impl ::std::ops::Deref<Target = deadpool_postgres::ClientWrapper>,
        rows: Vec<QueryStat>,
    ) -> anyhow::Result<()> {
        if rows.is_empty() {
            return Ok(());
        }
        let mut grouped_rows: ahash::AHashMap<_, Vec<QueryStat>> = ahash::AHashMap::new();
        for row in rows {
            grouped_rows.entry((row.database_id,)).or_default().push(row);
        }
        let sql = "COPY query_stats (database_id, toplevel, calls) FROM STDIN BINARY";
        let types = &[
            tokio_postgres::types::Type::INT8,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
        ];
        let stmt = db.copy_in(&db.prepare_cached(&sql).await?).await?;
        let writer = tokio_postgres::binary_copy::BinaryCopyInWriter::new(stmt, types);
        let mut writer = writer;
        #[allow(unused_mut)]
        let mut writer = unsafe {
            ::pin_utils::core_reexport::pin::Pin::new_unchecked(&mut writer)
        };
        for rows in grouped_rows.into_values() {
            writer
                .as_mut()
                .write(
                    &[
                        &rows[0].database_id,
                        &::pco::standalone::simpler_compress(
                                &rows.iter().map(|r| r.toplevel as u16).collect::<Vec<_>>(),
                                ::pco::DEFAULT_COMPRESSION_LEVEL,
                            )
                            .unwrap(),
                        &::pco::standalone::simpler_compress(
                                &rows.iter().map(|r| r.calls).collect::<Vec<_>>(),
                                ::pco::DEFAULT_COMPRESSION_LEVEL,
                            )
                            .unwrap(),
                    ],
                )
                .await?;
        }
        writer.finish().await?;
        Ok(())
    }
    /// Writes the data to disk, with the provided grouping closure applied.
    ///
    /// This can be used to improve the compression ratio and reduce read IO, for example
    /// by compacting real-time data into a single row per hour / day / week.
    pub async fn store_grouped<F, R>(
        db: &impl ::std::ops::Deref<Target = deadpool_postgres::ClientWrapper>,
        rows: Vec<QueryStat>,
        grouping: F,
    ) -> anyhow::Result<()>
    where
        F: Fn(&QueryStat) -> R,
        R: Eq + std::hash::Hash,
    {
        if rows.is_empty() {
            return Ok(());
        }
        let mut grouped_rows: ahash::AHashMap<_, Vec<QueryStat>> = ahash::AHashMap::new();
        for row in rows {
            grouped_rows.entry((row.database_id, grouping(&row))).or_default().push(row);
        }
        let sql = "COPY query_stats (database_id, toplevel, calls) FROM STDIN BINARY";
        let types = &[
            tokio_postgres::types::Type::INT8,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
        ];
        let stmt = db.copy_in(&db.prepare_cached(&sql).await?).await?;
        let writer = tokio_postgres::binary_copy::BinaryCopyInWriter::new(stmt, types);
        let mut writer = writer;
        #[allow(unused_mut)]
        let mut writer = unsafe {
            ::pin_utils::core_reexport::pin::Pin::new_unchecked(&mut writer)
        };
        for rows in grouped_rows.into_values() {
            writer
                .as_mut()
                .write(
                    &[
                        &rows[0].database_id,
                        &::pco::standalone::simpler_compress(
                                &rows.iter().map(|r| r.toplevel as u16).collect::<Vec<_>>(),
                                ::pco::DEFAULT_COMPRESSION_LEVEL,
                            )
                            .unwrap(),
                        &::pco::standalone::simpler_compress(
                                &rows.iter().map(|r| r.calls).collect::<Vec<_>>(),
                                ::pco::DEFAULT_COMPRESSION_LEVEL,
                            )
                            .unwrap(),
                    ],
                )
                .await?;
        }
        writer.finish().await?;
        Ok(())
    }
}
#[serde(deny_unknown_fields)]
/// Generated by pco_store to specify filters when loading [QueryStat]
pub struct Filter {
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    #[serde(
        deserialize_with = ":: serde_with :: As :: < serde_with :: DefaultOnNull < serde_with :: OneOrMany\n< :: serde_with :: Same > > > :: deserialize"
    )]
    pub database_id: Vec<i64>,
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    #[serde(
        deserialize_with = ":: serde_with :: As :: < serde_with :: DefaultOnNull < serde_with :: OneOrMany\n< :: serde_with :: Same > > > :: deserialize"
    )]
    pub toplevel: Vec<bool>,
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    #[serde(
        deserialize_with = ":: serde_with :: As :: < serde_with :: DefaultOnNull < serde_with :: OneOrMany\n< :: serde_with :: Same > > > :: deserialize"
    )]
    pub calls: Vec<i64>,
}
#[automatically_derived]
impl ::core::fmt::Debug for Filter {
    #[inline]
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        ::core::fmt::Formatter::debug_struct_field3_finish(
            f,
            "Filter",
            "database_id",
            &self.database_id,
            "toplevel",
            &self.toplevel,
            "calls",
            &&self.calls,
        )
    }
}
#[automatically_derived]
impl ::core::default::Default for Filter {
    #[inline]
    fn default() -> Filter {
        Filter {
            database_id: ::core::default::Default::default(),
            toplevel: ::core::default::Default::default(),
            calls: ::core::default::Default::default(),
        }
    }
}
#[doc(hidden)]
#[allow(
    non_upper_case_globals,
    unused_attributes,
    unused_qualifications,
    clippy::absolute_paths,
)]
const _: () = {
    #[allow(unused_extern_crates, clippy::useless_attribute)]
    extern crate serde as _serde;
    #[automatically_derived]
    impl<'de> _serde::Deserialize<'de> for Filter {
        fn deserialize<__D>(
            __deserializer: __D,
        ) -> _serde::__private228::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>,
        {
            #[allow(non_camel_case_types)]
            #[doc(hidden)]
            enum __Field {
                __field0,
                __field1,
                __field2,
            }
            #[doc(hidden)]
            struct __FieldVisitor;
            #[automatically_derived]
            impl<'de> _serde::de::Visitor<'de> for __FieldVisitor {
                type Value = __Field;
                fn expecting(
                    &self,
                    __formatter: &mut _serde::__private228::Formatter,
                ) -> _serde::__private228::fmt::Result {
                    _serde::__private228::Formatter::write_str(
                        __formatter,
                        "field identifier",
                    )
                }
                fn visit_u64<__E>(
                    self,
                    __value: u64,
                ) -> _serde::__private228::Result<Self::Value, __E>
                where
                    __E: _serde::de::Error,
                {
                    match __value {
                        0u64 => _serde::__private228::Ok(__Field::__field0),
                        1u64 => _serde::__private228::Ok(__Field::__field1),
                        2u64 => _serde::__private228::Ok(__Field::__field2),
                        _ => {
                            _serde::__private228::Err(
                                _serde::de::Error::invalid_value(
                                    _serde::de::Unexpected::Unsigned(__value),
                                    &"field index 0 <= i < 3",
                                ),
                            )
                        }
                    }
                }
                fn visit_str<__E>(
                    self,
                    __value: &str,
                ) -> _serde::__private228::Result<Self::Value, __E>
                where
                    __E: _serde::de::Error,
                {
                    match __value {
                        "database_id" => _serde::__private228::Ok(__Field::__field0),
                        "toplevel" => _serde::__private228::Ok(__Field::__field1),
                        "calls" => _serde::__private228::Ok(__Field::__field2),
                        _ => {
                            _serde::__private228::Err(
                                _serde::de::Error::unknown_field(__value, FIELDS),
                            )
                        }
                    }
                }
                fn visit_bytes<__E>(
                    self,
                    __value: &[u8],
                ) -> _serde::__private228::Result<Self::Value, __E>
                where
                    __E: _serde::de::Error,
                {
                    match __value {
                        b"database_id" => _serde::__private228::Ok(__Field::__field0),
                        b"toplevel" => _serde::__private228::Ok(__Field::__field1),
                        b"calls" => _serde::__private228::Ok(__Field::__field2),
                        _ => {
                            let __value = &_serde::__private228::from_utf8_lossy(
                                __value,
                            );
                            _serde::__private228::Err(
                                _serde::de::Error::unknown_field(__value, FIELDS),
                            )
                        }
                    }
                }
            }
            #[automatically_derived]
            impl<'de> _serde::Deserialize<'de> for __Field {
                #[inline]
                fn deserialize<__D>(
                    __deserializer: __D,
                ) -> _serde::__private228::Result<Self, __D::Error>
                where
                    __D: _serde::Deserializer<'de>,
                {
                    _serde::Deserializer::deserialize_identifier(
                        __deserializer,
                        __FieldVisitor,
                    )
                }
            }
            #[doc(hidden)]
            struct __Visitor<'de> {
                marker: _serde::__private228::PhantomData<Filter>,
                lifetime: _serde::__private228::PhantomData<&'de ()>,
            }
            #[automatically_derived]
            impl<'de> _serde::de::Visitor<'de> for __Visitor<'de> {
                type Value = Filter;
                fn expecting(
                    &self,
                    __formatter: &mut _serde::__private228::Formatter,
                ) -> _serde::__private228::fmt::Result {
                    _serde::__private228::Formatter::write_str(
                        __formatter,
                        "struct Filter",
                    )
                }
                #[inline]
                fn visit_seq<__A>(
                    self,
                    mut __seq: __A,
                ) -> _serde::__private228::Result<Self::Value, __A::Error>
                where
                    __A: _serde::de::SeqAccess<'de>,
                {
                    let __field0 = match {
                        #[doc(hidden)]
                        struct __DeserializeWith<'de> {
                            value: Vec<i64>,
                            phantom: _serde::__private228::PhantomData<Filter>,
                            lifetime: _serde::__private228::PhantomData<&'de ()>,
                        }
                        #[automatically_derived]
                        impl<'de> _serde::Deserialize<'de> for __DeserializeWith<'de> {
                            fn deserialize<__D>(
                                __deserializer: __D,
                            ) -> _serde::__private228::Result<Self, __D::Error>
                            where
                                __D: _serde::Deserializer<'de>,
                            {
                                _serde::__private228::Ok(__DeserializeWith {
                                    value: ::serde_with::As::<
                                        serde_with::DefaultOnNull<
                                            serde_with::OneOrMany<::serde_with::Same>,
                                        >,
                                    >::deserialize(__deserializer)?,
                                    phantom: _serde::__private228::PhantomData,
                                    lifetime: _serde::__private228::PhantomData,
                                })
                            }
                        }
                        _serde::__private228::Option::map(
                            _serde::de::SeqAccess::next_element::<
                                __DeserializeWith<'de>,
                            >(&mut __seq)?,
                            |__wrap| __wrap.value,
                        )
                    } {
                        _serde::__private228::Some(__value) => __value,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    let __field1 = match {
                        #[doc(hidden)]
                        struct __DeserializeWith<'de> {
                            value: Vec<bool>,
                            phantom: _serde::__private228::PhantomData<Filter>,
                            lifetime: _serde::__private228::PhantomData<&'de ()>,
                        }
                        #[automatically_derived]
                        impl<'de> _serde::Deserialize<'de> for __DeserializeWith<'de> {
                            fn deserialize<__D>(
                                __deserializer: __D,
                            ) -> _serde::__private228::Result<Self, __D::Error>
                            where
                                __D: _serde::Deserializer<'de>,
                            {
                                _serde::__private228::Ok(__DeserializeWith {
                                    value: ::serde_with::As::<
                                        serde_with::DefaultOnNull<
                                            serde_with::OneOrMany<::serde_with::Same>,
                                        >,
                                    >::deserialize(__deserializer)?,
                                    phantom: _serde::__private228::PhantomData,
                                    lifetime: _serde::__private228::PhantomData,
                                })
                            }
                        }
                        _serde::__private228::Option::map(
                            _serde::de::SeqAccess::next_element::<
                                __DeserializeWith<'de>,
                            >(&mut __seq)?,
                            |__wrap| __wrap.value,
                        )
                    } {
                        _serde::__private228::Some(__value) => __value,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    let __field2 = match {
                        #[doc(hidden)]
                        struct __DeserializeWith<'de> {
                            value: Vec<i64>,
                            phantom: _serde::__private228::PhantomData<Filter>,
                            lifetime: _serde::__private228::PhantomData<&'de ()>,
                        }
                        #[automatically_derived]
                        impl<'de> _serde::Deserialize<'de> for __DeserializeWith<'de> {
                            fn deserialize<__D>(
                                __deserializer: __D,
                            ) -> _serde::__private228::Result<Self, __D::Error>
                            where
                                __D: _serde::Deserializer<'de>,
                            {
                                _serde::__private228::Ok(__DeserializeWith {
                                    value: ::serde_with::As::<
                                        serde_with::DefaultOnNull<
                                            serde_with::OneOrMany<::serde_with::Same>,
                                        >,
                                    >::deserialize(__deserializer)?,
                                    phantom: _serde::__private228::PhantomData,
                                    lifetime: _serde::__private228::PhantomData,
                                })
                            }
                        }
                        _serde::__private228::Option::map(
                            _serde::de::SeqAccess::next_element::<
                                __DeserializeWith<'de>,
                            >(&mut __seq)?,
                            |__wrap| __wrap.value,
                        )
                    } {
                        _serde::__private228::Some(__value) => __value,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    _serde::__private228::Ok(Filter {
                        database_id: __field0,
                        toplevel: __field1,
                        calls: __field2,
                    })
                }
                #[inline]
                fn visit_map<__A>(
                    self,
                    mut __map: __A,
                ) -> _serde::__private228::Result<Self::Value, __A::Error>
                where
                    __A: _serde::de::MapAccess<'de>,
                {
                    let mut __field0: _serde::__private228::Option<Vec<i64>> = _serde::__private228::None;
                    let mut __field1: _serde::__private228::Option<Vec<bool>> = _serde::__private228::None;
                    let mut __field2: _serde::__private228::Option<Vec<i64>> = _serde::__private228::None;
                    while let _serde::__private228::Some(__key) = _serde::de::MapAccess::next_key::<
                        __Field,
                    >(&mut __map)? {
                        match __key {
                            __Field::__field0 => {
                                if _serde::__private228::Option::is_some(&__field0) {
                                    return _serde::__private228::Err(
                                        <__A::Error as _serde::de::Error>::duplicate_field(
                                            "database_id",
                                        ),
                                    );
                                }
                                __field0 = _serde::__private228::Some({
                                    #[doc(hidden)]
                                    struct __DeserializeWith<'de> {
                                        value: Vec<i64>,
                                        phantom: _serde::__private228::PhantomData<Filter>,
                                        lifetime: _serde::__private228::PhantomData<&'de ()>,
                                    }
                                    #[automatically_derived]
                                    impl<'de> _serde::Deserialize<'de>
                                    for __DeserializeWith<'de> {
                                        fn deserialize<__D>(
                                            __deserializer: __D,
                                        ) -> _serde::__private228::Result<Self, __D::Error>
                                        where
                                            __D: _serde::Deserializer<'de>,
                                        {
                                            _serde::__private228::Ok(__DeserializeWith {
                                                value: ::serde_with::As::<
                                                    serde_with::DefaultOnNull<
                                                        serde_with::OneOrMany<::serde_with::Same>,
                                                    >,
                                                >::deserialize(__deserializer)?,
                                                phantom: _serde::__private228::PhantomData,
                                                lifetime: _serde::__private228::PhantomData,
                                            })
                                        }
                                    }
                                    match _serde::de::MapAccess::next_value::<
                                        __DeserializeWith<'de>,
                                    >(&mut __map) {
                                        _serde::__private228::Ok(__wrapper) => __wrapper.value,
                                        _serde::__private228::Err(__err) => {
                                            return _serde::__private228::Err(__err);
                                        }
                                    }
                                });
                            }
                            __Field::__field1 => {
                                if _serde::__private228::Option::is_some(&__field1) {
                                    return _serde::__private228::Err(
                                        <__A::Error as _serde::de::Error>::duplicate_field(
                                            "toplevel",
                                        ),
                                    );
                                }
                                __field1 = _serde::__private228::Some({
                                    #[doc(hidden)]
                                    struct __DeserializeWith<'de> {
                                        value: Vec<bool>,
                                        phantom: _serde::__private228::PhantomData<Filter>,
                                        lifetime: _serde::__private228::PhantomData<&'de ()>,
                                    }
                                    #[automatically_derived]
                                    impl<'de> _serde::Deserialize<'de>
                                    for __DeserializeWith<'de> {
                                        fn deserialize<__D>(
                                            __deserializer: __D,
                                        ) -> _serde::__private228::Result<Self, __D::Error>
                                        where
                                            __D: _serde::Deserializer<'de>,
                                        {
                                            _serde::__private228::Ok(__DeserializeWith {
                                                value: ::serde_with::As::<
                                                    serde_with::DefaultOnNull<
                                                        serde_with::OneOrMany<::serde_with::Same>,
                                                    >,
                                                >::deserialize(__deserializer)?,
                                                phantom: _serde::__private228::PhantomData,
                                                lifetime: _serde::__private228::PhantomData,
                                            })
                                        }
                                    }
                                    match _serde::de::MapAccess::next_value::<
                                        __DeserializeWith<'de>,
                                    >(&mut __map) {
                                        _serde::__private228::Ok(__wrapper) => __wrapper.value,
                                        _serde::__private228::Err(__err) => {
                                            return _serde::__private228::Err(__err);
                                        }
                                    }
                                });
                            }
                            __Field::__field2 => {
                                if _serde::__private228::Option::is_some(&__field2) {
                                    return _serde::__private228::Err(
                                        <__A::Error as _serde::de::Error>::duplicate_field("calls"),
                                    );
                                }
                                __field2 = _serde::__private228::Some({
                                    #[doc(hidden)]
                                    struct __DeserializeWith<'de> {
                                        value: Vec<i64>,
                                        phantom: _serde::__private228::PhantomData<Filter>,
                                        lifetime: _serde::__private228::PhantomData<&'de ()>,
                                    }
                                    #[automatically_derived]
                                    impl<'de> _serde::Deserialize<'de>
                                    for __DeserializeWith<'de> {
                                        fn deserialize<__D>(
                                            __deserializer: __D,
                                        ) -> _serde::__private228::Result<Self, __D::Error>
                                        where
                                            __D: _serde::Deserializer<'de>,
                                        {
                                            _serde::__private228::Ok(__DeserializeWith {
                                                value: ::serde_with::As::<
                                                    serde_with::DefaultOnNull<
                                                        serde_with::OneOrMany<::serde_with::Same>,
                                                    >,
                                                >::deserialize(__deserializer)?,
                                                phantom: _serde::__private228::PhantomData,
                                                lifetime: _serde::__private228::PhantomData,
                                            })
                                        }
                                    }
                                    match _serde::de::MapAccess::next_value::<
                                        __DeserializeWith<'de>,
                                    >(&mut __map) {
                                        _serde::__private228::Ok(__wrapper) => __wrapper.value,
                                        _serde::__private228::Err(__err) => {
                                            return _serde::__private228::Err(__err);
                                        }
                                    }
                                });
                            }
                        }
                    }
                    let __field0 = match __field0 {
                        _serde::__private228::Some(__field0) => __field0,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    let __field1 = match __field1 {
                        _serde::__private228::Some(__field1) => __field1,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    let __field2 = match __field2 {
                        _serde::__private228::Some(__field2) => __field2,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    _serde::__private228::Ok(Filter {
                        database_id: __field0,
                        toplevel: __field1,
                        calls: __field2,
                    })
                }
            }
            #[doc(hidden)]
            const FIELDS: &'static [&'static str] = &[
                "database_id",
                "toplevel",
                "calls",
            ];
            _serde::Deserializer::deserialize_struct(
                __deserializer,
                "Filter",
                FIELDS,
                __Visitor {
                    marker: _serde::__private228::PhantomData::<Filter>,
                    lifetime: _serde::__private228::PhantomData,
                },
            )
        }
    }
};
#[automatically_derived]
impl ::core::clone::Clone for Filter {
    #[inline]
    fn clone(&self) -> Filter {
        Filter {
            database_id: ::core::clone::Clone::clone(&self.database_id),
            toplevel: ::core::clone::Clone::clone(&self.toplevel),
            calls: ::core::clone::Clone::clone(&self.calls),
        }
    }
}
#[automatically_derived]
impl ::core::marker::StructuralPartialEq for Filter {}
#[automatically_derived]
impl ::core::cmp::PartialEq for Filter {
    #[inline]
    fn eq(&self, other: &Filter) -> bool {
        self.database_id == other.database_id && self.toplevel == other.toplevel
            && self.calls == other.calls
    }
}
impl Filter {
    /// Builds new filter with the required fields defined by `group_by` and `timestamp`
    pub fn new(database_id: &[i64]) -> Self {
        Self {
            database_id: database_id.into(),
            ..Self::default()
        }
    }
    fn filter(&self, row: &QueryStat) -> bool {
        (self.database_id.is_empty() || self.database_id.contains(&row.database_id))
            && (self.toplevel.is_empty() || self.toplevel.contains(&row.toplevel))
            && (self.calls.is_empty() || self.calls.contains(&row.calls))
    }
}
