use serde::Deserialize as _;
#[pco_store::store(group_by = [id, name], timestamp = time)]
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Serde {
    pub id: Uuid,
    pub name: String,
    pub time: DateTime<Utc>,
    pub description: String,
    pub tags: Vec<String>,
    pub nums: Vec<i32>,
    pub map: BTreeMap<String, String>,
    pub json: serde_json::Value,
    pub model: Option<Box<Serde>>,
}
#[doc = concat!(
    " Generated by pco_store to store and load compressed versions of [",
    stringify!(Serde), "]"
)]
pub struct CompressedSerdes {
    filter: Option<Filter>,
    id: Uuid,
    name: String,
    time: Vec<u8>,
    description: Vec<u8>,
    tags: Vec<u8>,
    nums: Vec<u8>,
    map: Vec<u8>,
    json: Vec<u8>,
    model: Vec<u8>,
    start_at: DateTime<Utc>,
    end_at: DateTime<Utc>,
}
impl CompressedSerdes {
    pub fn new(rows: &Vec<Serde>) -> anyhow::Result<Self> {
        let time: Vec<_> = rows.iter().map(|s| s.time).collect();
        let start_at = *time.iter().min().unwrap();
        let end_at = *time.iter().max().unwrap();
        let time: Vec<u64> = time
            .into_iter()
            .map(|t| t.timestamp_micros() as u64)
            .collect();
        Ok(Self {
            id: rows[0].id.clone(),
            name: rows[0].name.clone(),
            time: ::pco::standalone::simple_compress(
                    &time,
                    &::pco::ChunkConfig::default(),
                )
                .unwrap(),
            start_at,
            end_at,
            description: serde_compress(
                rows.iter().map(|r| r.description.clone()).collect::<Vec<_>>(),
            )?,
            tags: serde_compress(
                rows.iter().map(|r| r.tags.clone()).collect::<Vec<_>>(),
            )?,
            nums: pco_compress_nested(
                rows
                    .iter()
                    .map(|r| r.nums.iter().map(|v| *v).collect::<Vec<_>>())
                    .collect::<Vec<_>>(),
            )?,
            map: serde_compress(rows.iter().map(|r| r.map.clone()).collect::<Vec<_>>())?,
            json: serde_compress(
                rows.iter().map(|r| r.json.clone()).collect::<Vec<_>>(),
            )?,
            model: serde_compress(
                rows.iter().map(|r| r.model.clone()).collect::<Vec<_>>(),
            )?,
            filter: None,
        })
    }
    /// Loads data for the specified filters.
    pub async fn load(
        db: &impl ::std::ops::Deref<Target = deadpool_postgres::ClientWrapper>,
        mut filter: Filter,
        fields: impl TryInto<Fields>,
    ) -> anyhow::Result<Vec<CompressedSerdes>> {
        let mut fields = fields
            .try_into()
            .map_err(|_| anyhow::Error::msg("unknown field"))?;
        fields.merge_filter(&filter);
        if filter.id.is_empty() {
            return Err(anyhow::Error::msg("id".to_string() + " is required"));
        }
        if filter.name.is_empty() {
            return Err(anyhow::Error::msg("name".to_string() + " is required"));
        }
        if filter.time.is_none() {
            return Err(anyhow::Error::msg("time".to_string() + " is required"));
        }
        filter.range_truncate()?;
        let sql = "SELECT ".to_string() + fields.select().as_str() + " FROM " + "serdes"
            + " WHERE "
            + "id = ANY($1) AND name = ANY($2) AND end_at >= $3 AND start_at <= $4";
        let mut results = Vec::new();
        for row in db
            .query(
                &db.prepare_cached(&sql).await?,
                &[
                    &filter.id,
                    &filter.name,
                    filter.time.as_ref().unwrap().start(),
                    filter.time.as_ref().unwrap().end(),
                ],
            )
            .await?
        {
            results.push(fields.load_from_row(row, Some(filter.clone()))?);
        }
        Ok(results)
    }
    /// Deletes data for the specified filters, returning it to the caller.
    ///
    /// Note that all rows are returned from [decompress][Self::decompress] even if post-decompress filters would normally apply.
    pub async fn delete(
        db: &impl ::std::ops::Deref<Target = deadpool_postgres::ClientWrapper>,
        mut filter: Filter,
        fields: impl TryInto<Fields>,
    ) -> anyhow::Result<Vec<CompressedSerdes>> {
        let mut fields = fields
            .try_into()
            .map_err(|_| anyhow::Error::msg("unknown field"))?;
        fields.merge_filter(&filter);
        if filter.id.is_empty() {
            return Err(anyhow::Error::msg("id".to_string() + " is required"));
        }
        if filter.name.is_empty() {
            return Err(anyhow::Error::msg("name".to_string() + " is required"));
        }
        if filter.time.is_none() {
            return Err(anyhow::Error::msg("time".to_string() + " is required"));
        }
        filter.range_truncate()?;
        let sql = "DELETE FROM ".to_string() + "serdes" + " WHERE "
            + "id = ANY($1) AND name = ANY($2) AND end_at >= $3 AND start_at <= $4"
            + " RETURNING " + fields.select().as_str();
        let mut results = Vec::new();
        for row in db
            .query(
                &db.prepare_cached(&sql).await?,
                &[
                    &filter.id,
                    &filter.name,
                    filter.time.as_ref().unwrap().start(),
                    filter.time.as_ref().unwrap().end(),
                ],
            )
            .await?
        {
            results.push(fields.load_from_row(row, None)?);
        }
        Ok(results)
    }
    /// Decompresses a group of data points.
    pub fn decompress(self) -> anyhow::Result<Vec<Serde>> {
        let mut results = Vec::new();
        let time: Vec<u64> = if self.time.is_empty() {
            Vec::new()
        } else {
            ::pco::standalone::simple_decompress(&self.time)?
        };
        let mut description = serde_decompress::<String>(&self.description);
        let mut tags = serde_decompress::<Vec<String>>(&self.tags);
        let mut nums: std::vec::IntoIter<Vec<i32>> = pco_decompress_nested(self.nums)?
            .into_iter();
        let mut map = serde_decompress::<BTreeMap<String, String>>(&self.map);
        let mut json = serde_decompress::<serde_json::Value>(&self.json);
        let mut model = serde_decompress::<Option<Box<Serde>>>(&self.model);
        let len = [time.len()].into_iter().max().unwrap_or(0);
        for index in 0..len {
            let row = Serde {
                id: self.id.clone(),
                name: self.name.clone(),
                time: chrono::DateTime::from_timestamp_micros(
                        time.get(index).cloned().unwrap_or_default() as i64,
                    )
                    .unwrap(),
                description: description.next().transpose()?.unwrap_or_default(),
                tags: tags.next().transpose()?.unwrap_or_default(),
                nums: nums.next().unwrap_or_default(),
                map: map.next().transpose()?.unwrap_or_default(),
                json: json.next().transpose()?.unwrap_or_default(),
                model: model.next().transpose()?.unwrap_or_default(),
            };
            if self.filter.as_ref().map(|f| f.matches(&row)) != Some(false) {
                results.push(row);
            }
        }
        Ok(results)
    }
    /// Writes the data to disk.
    pub async fn store(
        db: &impl ::std::ops::Deref<Target = deadpool_postgres::ClientWrapper>,
        rows: Vec<Serde>,
    ) -> anyhow::Result<()> {
        if rows.is_empty() {
            return Ok(());
        }
        let mut grouped_rows: ahash::AHashMap<_, Vec<Serde>> = ahash::AHashMap::new();
        for row in rows {
            grouped_rows
                .entry((row.id.clone(), row.name.clone()))
                .or_default()
                .push(row);
        }
        let sql = "COPY serdes (id, name, start_at, end_at, time, description, tags, nums, map, json, model) FROM STDIN BINARY";
        let types = &[
            tokio_postgres::types::Type::UUID,
            tokio_postgres::types::Type::TEXT,
            tokio_postgres::types::Type::TIMESTAMPTZ,
            tokio_postgres::types::Type::TIMESTAMPTZ,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
        ];
        let stmt = db.copy_in(&db.prepare_cached(&sql).await?).await?;
        let writer = tokio_postgres::binary_copy::BinaryCopyInWriter::new(stmt, types);
        futures::pin_mut!(writer);
        for rows in grouped_rows.into_values() {
            let row = Self::new(&rows)?;
            writer
                .as_mut()
                .write(
                    &[
                        &rows[0].id,
                        &rows[0].name,
                        &row.start_at,
                        &row.end_at,
                        &row.time,
                        &row.description,
                        &row.tags,
                        &row.nums,
                        &row.map,
                        &row.json,
                        &row.model,
                    ],
                )
                .await?;
        }
        writer.finish().await?;
        Ok(())
    }
    /// Writes the data to disk, with the provided grouping closure applied.
    ///
    /// This can be used to improve the compression ratio and reduce read IO, for example
    /// by compacting real-time data into a single row per hour / day / week.
    pub async fn store_grouped<F, R>(
        db: &impl ::std::ops::Deref<Target = deadpool_postgres::ClientWrapper>,
        rows: Vec<Serde>,
        grouping: F,
    ) -> anyhow::Result<()>
    where
        F: Fn(&Serde) -> R,
        R: Eq + std::hash::Hash,
    {
        if rows.is_empty() {
            return Ok(());
        }
        let mut grouped_rows: ahash::AHashMap<_, Vec<Serde>> = ahash::AHashMap::new();
        for row in rows {
            grouped_rows
                .entry((row.id.clone(), row.name.clone(), grouping(&row)))
                .or_default()
                .push(row);
        }
        let sql = "COPY serdes (id, name, start_at, end_at, time, description, tags, nums, map, json, model) FROM STDIN BINARY";
        let types = &[
            tokio_postgres::types::Type::UUID,
            tokio_postgres::types::Type::TEXT,
            tokio_postgres::types::Type::TIMESTAMPTZ,
            tokio_postgres::types::Type::TIMESTAMPTZ,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
        ];
        let stmt = db.copy_in(&db.prepare_cached(&sql).await?).await?;
        let writer = tokio_postgres::binary_copy::BinaryCopyInWriter::new(stmt, types);
        futures::pin_mut!(writer);
        for rows in grouped_rows.into_values() {
            let row = Self::new(&rows)?;
            writer
                .as_mut()
                .write(
                    &[
                        &rows[0].id,
                        &rows[0].name,
                        &row.start_at,
                        &row.end_at,
                        &row.time,
                        &row.description,
                        &row.tags,
                        &row.nums,
                        &row.map,
                        &row.json,
                        &row.model,
                    ],
                )
                .await?;
        }
        writer.finish().await?;
        Ok(())
    }
}
#[serde_with::serde_as]
#[derive(Debug, Default, serde::Deserialize, Clone, PartialEq)]
#[serde(deny_unknown_fields)]
#[doc = concat!(
    " Generated by pco_store to specify filters when loading [", stringify!(Serde), "]"
)]
pub struct Filter {
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    pub id: Vec<Uuid>,
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    pub name: Vec<String>,
    #[serde(deserialize_with = "deserialize_time_range")]
    pub time: Option<std::ops::RangeInclusive<DateTime<Utc>>>,
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    pub description: Vec<String>,
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    pub tags: Vec<Vec<String>>,
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    pub nums: Vec<Vec<i32>>,
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    pub map: Vec<BTreeMap<String, String>>,
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    pub json: Vec<serde_json::Value>,
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    pub model: Vec<Option<Box<Serde>>>,
}
impl Filter {
    /// Builds new filter with the required fields defined by `group_by` and `timestamp`
    pub fn new(
        id: &[Uuid],
        name: &[String],
        time: std::ops::RangeInclusive<DateTime<Utc>>,
    ) -> Self {
        Self {
            id: id.into(),
            name: name.into(),
            time: Some(time),
            ..Self::default()
        }
    }
    fn matches(&self, row: &Serde) -> bool {
        (self.id.is_empty() || self.id.contains(&row.id))
            && (self.name.is_empty() || self.name.contains(&row.name))
            && self.time.as_ref().map(|t| t.contains(&row.time)) != Some(false)
            && (self.description.is_empty()
                || self.description.contains(&row.description))
            && (self.tags.is_empty() || self.tags.contains(&row.tags))
            && (self.nums.is_empty() || self.nums.contains(&row.nums))
            && (self.map.is_empty() || self.map.contains(&row.map))
            && (self.json.is_empty() || self.json.contains(&row.json))
            && (self.model.is_empty() || self.model.contains(&row.model))
    }
    /// Convenience function to unwrap the timestamp range lower and upper bounds
    pub fn range_bounds(&self) -> anyhow::Result<(DateTime<Utc>, DateTime<Utc>)> {
        use anyhow::Context;
        let timestamp = self.time.clone().context("no timestamp")?;
        Ok((*timestamp.start(), *timestamp.end()))
    }
    /// Convenience function to return the amount of time the filter covers
    pub fn range_duration(&self) -> anyhow::Result<chrono::Duration> {
        let (start, end) = self.range_bounds()?;
        Ok(end - start)
    }
    /// Shifts the filtered time range. This for example makes it easier
    /// to perform two queries: once for "today", and one for "today, 7 days ago".
    /// In that example the second query would do `filter.shift(Duration::days(-7))`
    pub fn range_shift(&mut self, duration: chrono::Duration) -> anyhow::Result<()> {
        use std::ops::Add;
        let (start, end) = self.range_bounds()?;
        self.time = Some(start.add(duration)..=end.add(duration));
        Ok(())
    }
    /// Postgres doesn't support nanosecond precision and nor does MacOS, so this
    /// truncates nanosecond precision for timestamp comparisons
    fn range_truncate(&mut self) -> anyhow::Result<()> {
        let (start, end) = self.range_bounds()?;
        self.time = Some(Self::truncate_nanos(start)?..=Self::truncate_nanos(end)?);
        Ok(())
    }
    fn truncate_nanos(time: DateTime<Utc>) -> anyhow::Result<DateTime<Utc>> {
        use anyhow::Context;
        Ok(
            chrono::DateTime::from_timestamp_micros(time.timestamp_micros())
                .context("out of range")?,
        )
    }
}
#[derive(Clone, Copy, Debug, PartialEq)]
#[doc = concat!(
    " Generated by pco_store to choose which fields to decompress when loading [",
    stringify!(Serde), "]"
)]
pub struct Fields {
    id: bool,
    name: bool,
    start_at: bool,
    end_at: bool,
    time: bool,
    description: bool,
    tags: bool,
    nums: bool,
    map: bool,
    json: bool,
    model: bool,
}
impl Fields {
    pub fn new(fields: &[&str]) -> anyhow::Result<Self> {
        fields.try_into().map_err(|e| anyhow::Error::msg(e))
    }
    pub fn required() -> Self {
        Self {
            id: true,
            name: true,
            start_at: true,
            end_at: true,
            time: true,
            description: false,
            tags: false,
            nums: false,
            map: false,
            json: false,
            model: false,
        }
    }
    fn merge_filter(&mut self, filter: &Filter) {
        (!filter.description.is_empty()).then(|| self.description = true);
        (!filter.tags.is_empty()).then(|| self.tags = true);
        (!filter.nums.is_empty()).then(|| self.nums = true);
        (!filter.map.is_empty()).then(|| self.map = true);
        (!filter.json.is_empty()).then(|| self.json = true);
        (!filter.model.is_empty()).then(|| self.model = true);
    }
    fn select(&self) -> String {
        let mut fields = Vec::new();
        self.id.then(|| fields.push("id"));
        self.name.then(|| fields.push("name"));
        fields.extend(["start_at", "end_at", "time"]);
        self.description.then(|| fields.push("description"));
        self.tags.then(|| fields.push("tags"));
        self.nums.then(|| fields.push("nums"));
        self.map.then(|| fields.push("map"));
        self.json.then(|| fields.push("json"));
        self.model.then(|| fields.push("model"));
        fields.join(", ")
    }
    fn load_from_row(
        &self,
        row: tokio_postgres::Row,
        filter: Option<Filter>,
    ) -> anyhow::Result<CompressedSerdes> {
        let mut index = 0;
        Ok(CompressedSerdes {
            filter,
            id: if self.id {
                let v = row.get(index);
                index += 1;
                v
            } else {
                Default::default()
            },
            name: if self.name {
                let v = row.get(index);
                index += 1;
                v
            } else {
                Default::default()
            },
            start_at: {
                let v = row.get(index);
                index += 1;
                v
            },
            end_at: {
                let v = row.get(index);
                index += 1;
                v
            },
            time: {
                let v = row.get(index);
                index += 1;
                v
            },
            description: if self.description {
                let v = row.get(index);
                index += 1;
                v
            } else {
                Default::default()
            },
            tags: if self.tags {
                let v = row.get(index);
                index += 1;
                v
            } else {
                Default::default()
            },
            nums: if self.nums {
                let v = row.get(index);
                index += 1;
                v
            } else {
                Default::default()
            },
            map: if self.map {
                let v = row.get(index);
                index += 1;
                v
            } else {
                Default::default()
            },
            json: if self.json {
                let v = row.get(index);
                index += 1;
                v
            } else {
                Default::default()
            },
            model: if self.model {
                let v = row.get(index);
                index += 1;
                v
            } else {
                Default::default()
            },
        })
    }
}
impl Default for Fields {
    fn default() -> Self {
        Self {
            id: true,
            name: true,
            start_at: true,
            end_at: true,
            time: true,
            description: true,
            tags: true,
            nums: true,
            map: true,
            json: true,
            model: true,
        }
    }
}
impl TryFrom<&[&str]> for Fields {
    type Error = &'static str;
    fn try_from(input: &[&str]) -> Result<Self, Self::Error> {
        let mut fields = Self::required();
        for s in input {
            match *s {
                "id" => fields.id = true,
                "name" => fields.name = true,
                "description" => fields.description = true,
                "tags" => fields.tags = true,
                "nums" => fields.nums = true,
                "map" => fields.map = true,
                "json" => fields.json = true,
                "model" => fields.model = true,
                _ => return Err("unknown field"),
            }
        }
        Ok(fields)
    }
}
impl<const N: usize> TryFrom<&[&str; N]> for Fields {
    type Error = &'static str;
    fn try_from(input: &[&str; N]) -> Result<Self, Self::Error> {
        Self::try_from(&input[..])
    }
}
impl TryFrom<Vec<String>> for Fields {
    type Error = &'static str;
    fn try_from(input: Vec<String>) -> Result<Self, Self::Error> {
        let input: Vec<_> = input.iter().map(|s| s.as_str()).collect();
        Self::try_from(input.as_slice())
    }
}
impl From<()> for Fields {
    fn from(_: ()) -> Self {
        Self::default()
    }
}
impl<'de> serde::Deserialize<'de> for Fields {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        deserializer.deserialize_any(FieldsVisitor)
    }
}
struct FieldsVisitor;
impl<'de> serde::de::Visitor<'de> for FieldsVisitor {
    type Value = Fields;
    fn expecting(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
        formatter.write_str("an array of strings matching the struct fields")
    }
    fn visit_seq<A>(self, mut seq: A) -> Result<Self::Value, A::Error>
    where
        A: serde::de::SeqAccess<'de>,
    {
        let mut fields = Vec::new();
        while let Some(field) = seq.next_element()? {
            fields.push(field);
        }
        Fields::try_from(fields).map_err(serde::de::Error::custom)
    }
    fn visit_unit<E>(self) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        Ok(Fields::default())
    }
}
/// Deserializes many different time range formats:
/// - an array with two strings becomes a normal time range: ["a", "b"] -> a..=b
/// - an array with one string becomes a single-value time range: ["a"] -> a..=a
/// - a string literal becomes a single-value time range:           "a" -> a..=a
fn deserialize_time_range<'de, D>(
    deserializer: D,
) -> Result<Option<std::ops::RangeInclusive<DateTime<Utc>>>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    Ok(TimeRange::deserialize(deserializer)?.0)
}
#[derive(Debug, PartialEq)]
struct TimeRange(Option<std::ops::RangeInclusive<DateTime<Utc>>>);
impl<'de> serde::Deserialize<'de> for TimeRange {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        deserializer.deserialize_any(TimeRangeVisitor)
    }
}
struct TimeRangeVisitor;
impl<'de> serde::de::Visitor<'de> for TimeRangeVisitor {
    type Value = TimeRange;
    fn expecting(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
        formatter.write_str("a single time string or an array with 1-2 time strings")
    }
    fn visit_str<E>(self, value: &str) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        if value.is_empty() {
            return Ok(TimeRange(None));
        }
        match serde::Deserialize::deserialize(
            serde::de::value::StrDeserializer::<E>::new(value),
        ) {
            Ok(start) => Ok(TimeRange(Some(start..=start))),
            Err(err) => {
                Err(
                    E::custom(
                        "invalid time format: ".to_string() + err.to_string().as_str(),
                    ),
                )
            }
        }
    }
    fn visit_seq<A>(self, mut seq: A) -> Result<Self::Value, A::Error>
    where
        A: serde::de::SeqAccess<'de>,
    {
        let start = match seq.next_element::<Option<DateTime<Utc>>>()? {
            Some(Some(time)) => time,
            Some(None) | None => return Ok(TimeRange(None)),
        };
        let end = match seq.next_element::<Option<DateTime<Utc>>>()? {
            Some(Some(time)) => time,
            Some(None) | None => start,
        };
        Ok(TimeRange(Some(start..=end)))
    }
    fn visit_unit<E>(self) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        Ok(TimeRange(None))
    }
}
fn serde_compress<T>(items: Vec<T>) -> anyhow::Result<Vec<u8>>
where
    T: serde::Serialize,
{
    use std::io::Write;
    let mut output = Vec::new();
    let mut encoder = zstd::stream::write::Encoder::new(&mut output, 3)?;
    for item in items {
        rmp_serde::encode::write(&mut encoder, &item)?;
    }
    encoder.finish()?;
    Ok(output)
}
fn serde_decompress<T>(input: &[u8]) -> impl Iterator<Item = anyhow::Result<T>> + '_
where
    T: for<'de> serde::Deserialize<'de> + 'static,
{
    let decoder = match zstd::stream::read::Decoder::new(input) {
        Ok(d) => d,
        Err(e) => {
            return Box::new(std::iter::once(Err(e.into())))
                as Box<dyn Iterator<Item = _>>;
        }
    };
    let buffered = std::io::BufReader::with_capacity(128 * 1024, decoder);
    let mut de = rmp_serde::decode::Deserializer::new(buffered);
    Box::new(
        std::iter::from_fn(move || match serde::Deserialize::deserialize(&mut de) {
            Ok(item) => Some(Ok(item)),
            Err(
                rmp_serde::decode::Error::InvalidMarkerRead(ref e),
            ) if e.kind() == std::io::ErrorKind::UnexpectedEof => None,
            Err(e) => Some(Err(e.into())),
        }),
    )
}
fn pco_compress_nested<T>(nested_values: Vec<Vec<T>>) -> anyhow::Result<Vec<u8>>
where
    T: ::pco::data_types::Number,
{
    let mut lengths = Vec::new();
    let mut values = Vec::new();
    for vals in nested_values {
        lengths.push(vals.len() as u64);
        values.extend(vals);
    }
    let length_bytes = ::pco::standalone::simple_compress(
        &lengths,
        &::pco::ChunkConfig::default(),
    )?;
    let value_bytes = ::pco::standalone::simple_compress(
        &values,
        &::pco::ChunkConfig::default(),
    )?;
    let (length_bytes, value_bytes) = (
        serde_bytes::Bytes::new(&length_bytes),
        serde_bytes::Bytes::new(&value_bytes),
    );
    Ok(rmp_serde::to_vec(&(length_bytes, value_bytes))?)
}
fn pco_decompress_nested<T>(bytes: Vec<u8>) -> anyhow::Result<Vec<Vec<T>>>
where
    T: ::pco::data_types::Number,
{
    let (length_bytes, value_bytes): (Vec<u8>, Vec<u8>) = rmp_serde::from_slice(&bytes)?;
    let lengths = ::pco::standalone::simple_decompress::<u64>(&length_bytes)?;
    let values = ::pco::standalone::simple_decompress::<T>(&value_bytes)?;
    let mut values = values.into_iter();
    let mut nested_values = Vec::with_capacity(lengths.len());
    for length in lengths {
        nested_values.push(values.by_ref().take(length as usize).collect::<Vec<T>>());
    }
    Ok(nested_values)
}
