use chrono::{DateTime, Utc};
use uuid::Uuid;
use serde::Deserialize as _;
pub struct SystemStorageStat {
    pub server_id: Uuid,
    pub granularity: i32,
    pub mountpoint: String,
    pub collected_at: DateTime<Utc>,
    pub bytes_available: i64,
    pub bytes_total: i64,
    pub queue_depth: i64,
    pub read_latency: f64,
    pub write_latency: f64,
}
/// Generated by pco_store to store and load compressed versions of [SystemStorageStat]
pub struct CompressedSystemStorageStats {
    filter: Option<Filter>,
    server_id: Uuid,
    granularity: i32,
    mountpoint: String,
    collected_at: Vec<u8>,
    bytes_available: Vec<u8>,
    bytes_total: Vec<u8>,
    queue_depth: Vec<u8>,
    read_latency: Vec<u8>,
    write_latency: Vec<u8>,
}
impl CompressedSystemStorageStats {
    /// Loads data for the specified filters.
    #[track_caller]
    pub async fn load(
        db: &impl ::std::ops::Deref<Target = deadpool_postgres::ClientWrapper>,
        mut filter: Filter,
        fields: impl TryInto<Fields>,
    ) -> anyhow::Result<Vec<CompressedSystemStorageStats>> {
        let mut fields = fields
            .try_into()
            .map_err(|_| anyhow::Error::msg("unknown field"))?;
        fields.merge_filter(&filter);
        if filter.server_id.is_empty() {
            return Err(anyhow::Error::msg("server_id".to_string() + " is required"));
        }
        if filter.granularity.is_empty() {
            return Err(anyhow::Error::msg("granularity".to_string() + " is required"));
        }
        if filter.mountpoint.is_empty() {
            return Err(anyhow::Error::msg("mountpoint".to_string() + " is required"));
        }
        if filter.collected_at.is_none() {
            return Err(anyhow::Error::msg("collected_at".to_string() + " is required"));
        }
        filter.range_truncate()?;
        let location = std::panic::Location::caller();
        let comment = "/* line:".to_string() + location.file() + ":"
            + location.line().to_string().as_str() + " */ ";
        let sql = comment + "SELECT " + fields.select().as_str() + " FROM "
            + "system_storage_stats" + " WHERE "
            + "server_id = ANY($1) AND granularity = ANY($2) AND mountpoint = ANY($3) AND end_at >= $4 AND start_at <= $5";
        let mut results = Vec::new();
        for row in db
            .query(
                &db.prepare_cached(&sql).await?,
                &[
                    &filter.server_id,
                    &filter.granularity,
                    &filter.mountpoint,
                    filter.collected_at.as_ref().unwrap().start(),
                    filter.collected_at.as_ref().unwrap().end(),
                ],
            )
            .await?
        {
            results.push(fields.load_from_row(row, Some(filter.clone()))?);
        }
        Ok(results)
    }
    /// Deletes data for the specified filters, returning it to the caller.
    ///
    /// Note that all rows are returned from [decompress][Self::decompress] even if post-decompress filters would normally apply.
    #[track_caller]
    pub async fn delete(
        db: &impl ::std::ops::Deref<Target = deadpool_postgres::ClientWrapper>,
        mut filter: Filter,
        fields: impl TryInto<Fields>,
    ) -> anyhow::Result<Vec<CompressedSystemStorageStats>> {
        let mut fields = fields
            .try_into()
            .map_err(|_| anyhow::Error::msg("unknown field"))?;
        fields.merge_filter(&filter);
        if filter.server_id.is_empty() {
            return Err(anyhow::Error::msg("server_id".to_string() + " is required"));
        }
        if filter.granularity.is_empty() {
            return Err(anyhow::Error::msg("granularity".to_string() + " is required"));
        }
        if filter.mountpoint.is_empty() {
            return Err(anyhow::Error::msg("mountpoint".to_string() + " is required"));
        }
        if filter.collected_at.is_none() {
            return Err(anyhow::Error::msg("collected_at".to_string() + " is required"));
        }
        filter.range_truncate()?;
        let location = std::panic::Location::caller();
        let comment = "/* line:".to_string() + location.file() + ":"
            + location.line().to_string().as_str() + " */ ";
        let sql = comment + "DELETE FROM " + "system_storage_stats" + " WHERE "
            + "server_id = ANY($1) AND granularity = ANY($2) AND mountpoint = ANY($3) AND end_at >= $4 AND start_at <= $5"
            + " RETURNING " + fields.select().as_str();
        let mut results = Vec::new();
        for row in db
            .query(
                &db.prepare_cached(&sql).await?,
                &[
                    &filter.server_id,
                    &filter.granularity,
                    &filter.mountpoint,
                    filter.collected_at.as_ref().unwrap().start(),
                    filter.collected_at.as_ref().unwrap().end(),
                ],
            )
            .await?
        {
            results.push(fields.load_from_row(row, None)?);
        }
        Ok(results)
    }
    /// Decompresses a group of data points.
    pub fn decompress(self) -> anyhow::Result<Vec<SystemStorageStat>> {
        let mut results = Vec::new();
        let collected_at: Vec<u64> = if self.collected_at.is_empty() {
            Vec::new()
        } else {
            ::pco::standalone::simple_decompress(&self.collected_at)?
        };
        let bytes_available: Vec<i64> = if self.bytes_available.is_empty() {
            Vec::new()
        } else {
            ::pco::standalone::simple_decompress(&self.bytes_available)?
        };
        let bytes_total: Vec<i64> = if self.bytes_total.is_empty() {
            Vec::new()
        } else {
            ::pco::standalone::simple_decompress(&self.bytes_total)?
        };
        let queue_depth: Vec<i64> = if self.queue_depth.is_empty() {
            Vec::new()
        } else {
            ::pco::standalone::simple_decompress(&self.queue_depth)?
        };
        let read_latency: Vec<i64> = if self.read_latency.is_empty() {
            Vec::new()
        } else {
            ::pco::standalone::simple_decompress(&self.read_latency)?
        };
        let write_latency: Vec<i64> = if self.write_latency.is_empty() {
            Vec::new()
        } else {
            ::pco::standalone::simple_decompress(&self.write_latency)?
        };
        let len = [
            collected_at.len(),
            bytes_available.len(),
            bytes_total.len(),
            queue_depth.len(),
            read_latency.len(),
            write_latency.len(),
        ]
            .into_iter()
            .max()
            .unwrap_or(0);
        for index in 0..len {
            let row = SystemStorageStat {
                server_id: self.server_id.clone(),
                granularity: self.granularity.clone(),
                mountpoint: self.mountpoint.clone(),
                collected_at: chrono::DateTime::from_timestamp_micros(
                        collected_at[index] as i64,
                    )
                    .unwrap(),
                bytes_available: bytes_available.get(index).cloned().unwrap_or_default(),
                bytes_total: bytes_total.get(index).cloned().unwrap_or_default(),
                queue_depth: queue_depth.get(index).cloned().unwrap_or_default(),
                read_latency: read_latency.get(index).cloned().unwrap_or_default() as f64
                    / 100f32 as f64,
                write_latency: write_latency.get(index).cloned().unwrap_or_default()
                    as f64 / 100f32 as f64,
            };
            if self.filter.as_ref().map(|f| f.matches(&row)) != Some(false) {
                results.push(row);
            }
        }
        Ok(results)
    }
    /// Writes the data to disk.
    #[track_caller]
    pub async fn store(
        db: &impl ::std::ops::Deref<Target = deadpool_postgres::ClientWrapper>,
        rows: Vec<SystemStorageStat>,
    ) -> anyhow::Result<()> {
        if rows.is_empty() {
            return Ok(());
        }
        let mut grouped_rows: ahash::AHashMap<_, Vec<SystemStorageStat>> = ahash::AHashMap::new();
        for row in rows {
            grouped_rows
                .entry((
                    row.server_id.clone(),
                    row.granularity.clone(),
                    row.mountpoint.clone(),
                ))
                .or_default()
                .push(row);
        }
        let location = std::panic::Location::caller();
        let comment = "/* line:".to_string() + location.file() + ":"
            + location.line().to_string().as_str() + " */ ";
        let sql = comment
            + "COPY system_storage_stats (server_id, granularity, mountpoint, start_at, end_at, collected_at, bytes_available, bytes_total, queue_depth, read_latency, write_latency) FROM STDIN BINARY";
        let types = &[
            tokio_postgres::types::Type::UUID,
            tokio_postgres::types::Type::INT4,
            tokio_postgres::types::Type::TEXT,
            tokio_postgres::types::Type::TIMESTAMPTZ,
            tokio_postgres::types::Type::TIMESTAMPTZ,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
        ];
        let stmt = db.copy_in(&db.prepare_cached(&sql).await?).await?;
        let writer = tokio_postgres::binary_copy::BinaryCopyInWriter::new(stmt, types);
        let mut writer = writer;
        #[allow(unused_mut)]
        let mut writer = unsafe {
            ::pin_utils::core_reexport::pin::Pin::new_unchecked(&mut writer)
        };
        for rows in grouped_rows.into_values() {
            let collected_at: Vec<_> = rows.iter().map(|s| s.collected_at).collect();
            let start_at = *collected_at.iter().min().unwrap();
            let end_at = *collected_at.iter().max().unwrap();
            let collected_at: Vec<u64> = collected_at
                .into_iter()
                .map(|t| t.timestamp_micros() as u64)
                .collect();
            writer
                .as_mut()
                .write(
                    &[
                        &rows[0].server_id,
                        &rows[0].granularity,
                        &rows[0].mountpoint,
                        &start_at,
                        &end_at,
                        &::pco::standalone::simpler_compress(
                                &collected_at,
                                ::pco::DEFAULT_COMPRESSION_LEVEL,
                            )
                            .unwrap(),
                        &::pco::standalone::simpler_compress(
                                &rows.iter().map(|r| r.bytes_available).collect::<Vec<_>>(),
                                ::pco::DEFAULT_COMPRESSION_LEVEL,
                            )
                            .unwrap(),
                        &::pco::standalone::simpler_compress(
                                &rows.iter().map(|r| r.bytes_total).collect::<Vec<_>>(),
                                ::pco::DEFAULT_COMPRESSION_LEVEL,
                            )
                            .unwrap(),
                        &::pco::standalone::simpler_compress(
                                &rows.iter().map(|r| r.queue_depth).collect::<Vec<_>>(),
                                ::pco::DEFAULT_COMPRESSION_LEVEL,
                            )
                            .unwrap(),
                        &::pco::standalone::simpler_compress(
                                &rows
                                    .iter()
                                    .map(|r| (r.read_latency * 100f32 as f64).round() as i64)
                                    .collect::<Vec<_>>(),
                                ::pco::DEFAULT_COMPRESSION_LEVEL,
                            )
                            .unwrap(),
                        &::pco::standalone::simpler_compress(
                                &rows
                                    .iter()
                                    .map(|r| (r.write_latency * 100f32 as f64).round() as i64)
                                    .collect::<Vec<_>>(),
                                ::pco::DEFAULT_COMPRESSION_LEVEL,
                            )
                            .unwrap(),
                    ],
                )
                .await?;
        }
        writer.finish().await?;
        Ok(())
    }
    /// Writes the data to disk, with the provided grouping closure applied.
    ///
    /// This can be used to improve the compression ratio and reduce read IO, for example
    /// by compacting real-time data into a single row per hour / day / week.
    #[track_caller]
    pub async fn store_grouped<F, R>(
        db: &impl ::std::ops::Deref<Target = deadpool_postgres::ClientWrapper>,
        rows: Vec<SystemStorageStat>,
        grouping: F,
    ) -> anyhow::Result<()>
    where
        F: Fn(&SystemStorageStat) -> R,
        R: Eq + std::hash::Hash,
    {
        if rows.is_empty() {
            return Ok(());
        }
        let mut grouped_rows: ahash::AHashMap<_, Vec<SystemStorageStat>> = ahash::AHashMap::new();
        for row in rows {
            grouped_rows
                .entry((
                    row.server_id.clone(),
                    row.granularity.clone(),
                    row.mountpoint.clone(),
                    grouping(&row),
                ))
                .or_default()
                .push(row);
        }
        let location = std::panic::Location::caller();
        let comment = "/* line:".to_string() + location.file() + ":"
            + location.line().to_string().as_str() + " */ ";
        let sql = comment
            + "COPY system_storage_stats (server_id, granularity, mountpoint, start_at, end_at, collected_at, bytes_available, bytes_total, queue_depth, read_latency, write_latency) FROM STDIN BINARY";
        let types = &[
            tokio_postgres::types::Type::UUID,
            tokio_postgres::types::Type::INT4,
            tokio_postgres::types::Type::TEXT,
            tokio_postgres::types::Type::TIMESTAMPTZ,
            tokio_postgres::types::Type::TIMESTAMPTZ,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
            tokio_postgres::types::Type::BYTEA,
        ];
        let stmt = db.copy_in(&db.prepare_cached(&sql).await?).await?;
        let writer = tokio_postgres::binary_copy::BinaryCopyInWriter::new(stmt, types);
        let mut writer = writer;
        #[allow(unused_mut)]
        let mut writer = unsafe {
            ::pin_utils::core_reexport::pin::Pin::new_unchecked(&mut writer)
        };
        for rows in grouped_rows.into_values() {
            let collected_at: Vec<_> = rows.iter().map(|s| s.collected_at).collect();
            let start_at = *collected_at.iter().min().unwrap();
            let end_at = *collected_at.iter().max().unwrap();
            let collected_at: Vec<u64> = collected_at
                .into_iter()
                .map(|t| t.timestamp_micros() as u64)
                .collect();
            writer
                .as_mut()
                .write(
                    &[
                        &rows[0].server_id,
                        &rows[0].granularity,
                        &rows[0].mountpoint,
                        &start_at,
                        &end_at,
                        &::pco::standalone::simpler_compress(
                                &collected_at,
                                ::pco::DEFAULT_COMPRESSION_LEVEL,
                            )
                            .unwrap(),
                        &::pco::standalone::simpler_compress(
                                &rows.iter().map(|r| r.bytes_available).collect::<Vec<_>>(),
                                ::pco::DEFAULT_COMPRESSION_LEVEL,
                            )
                            .unwrap(),
                        &::pco::standalone::simpler_compress(
                                &rows.iter().map(|r| r.bytes_total).collect::<Vec<_>>(),
                                ::pco::DEFAULT_COMPRESSION_LEVEL,
                            )
                            .unwrap(),
                        &::pco::standalone::simpler_compress(
                                &rows.iter().map(|r| r.queue_depth).collect::<Vec<_>>(),
                                ::pco::DEFAULT_COMPRESSION_LEVEL,
                            )
                            .unwrap(),
                        &::pco::standalone::simpler_compress(
                                &rows
                                    .iter()
                                    .map(|r| (r.read_latency * 100f32 as f64).round() as i64)
                                    .collect::<Vec<_>>(),
                                ::pco::DEFAULT_COMPRESSION_LEVEL,
                            )
                            .unwrap(),
                        &::pco::standalone::simpler_compress(
                                &rows
                                    .iter()
                                    .map(|r| (r.write_latency * 100f32 as f64).round() as i64)
                                    .collect::<Vec<_>>(),
                                ::pco::DEFAULT_COMPRESSION_LEVEL,
                            )
                            .unwrap(),
                    ],
                )
                .await?;
        }
        writer.finish().await?;
        Ok(())
    }
}
#[serde(deny_unknown_fields)]
/// Generated by pco_store to specify filters when loading [SystemStorageStat]
pub struct Filter {
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    #[serde(
        deserialize_with = ":: serde_with :: As :: < serde_with :: DefaultOnNull < serde_with :: OneOrMany\n< :: serde_with :: Same > > > :: deserialize"
    )]
    pub server_id: Vec<Uuid>,
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    #[serde(
        deserialize_with = ":: serde_with :: As :: < serde_with :: DefaultOnNull < serde_with :: OneOrMany\n< :: serde_with :: Same > > > :: deserialize"
    )]
    pub granularity: Vec<i32>,
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    #[serde(
        deserialize_with = ":: serde_with :: As :: < serde_with :: DefaultOnNull < serde_with :: OneOrMany\n< :: serde_with :: Same > > > :: deserialize"
    )]
    pub mountpoint: Vec<String>,
    #[serde(deserialize_with = "deserialize_time_range")]
    pub collected_at: Option<std::ops::RangeInclusive<DateTime<Utc>>>,
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    #[serde(
        deserialize_with = ":: serde_with :: As :: < serde_with :: DefaultOnNull < serde_with :: OneOrMany\n< :: serde_with :: Same > > > :: deserialize"
    )]
    pub bytes_available: Vec<i64>,
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    #[serde(
        deserialize_with = ":: serde_with :: As :: < serde_with :: DefaultOnNull < serde_with :: OneOrMany\n< :: serde_with :: Same > > > :: deserialize"
    )]
    pub bytes_total: Vec<i64>,
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    #[serde(
        deserialize_with = ":: serde_with :: As :: < serde_with :: DefaultOnNull < serde_with :: OneOrMany\n< :: serde_with :: Same > > > :: deserialize"
    )]
    pub queue_depth: Vec<i64>,
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    #[serde(
        deserialize_with = ":: serde_with :: As :: < serde_with :: DefaultOnNull < serde_with :: OneOrMany\n< :: serde_with :: Same > > > :: deserialize"
    )]
    pub read_latency: Vec<f64>,
    #[serde(default)]
    #[serde_as(deserialize_as = "serde_with::DefaultOnNull<serde_with::OneOrMany<_>>")]
    #[serde(
        deserialize_with = ":: serde_with :: As :: < serde_with :: DefaultOnNull < serde_with :: OneOrMany\n< :: serde_with :: Same > > > :: deserialize"
    )]
    pub write_latency: Vec<f64>,
}
#[automatically_derived]
impl ::core::fmt::Debug for Filter {
    #[inline]
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        let names: &'static _ = &[
            "server_id",
            "granularity",
            "mountpoint",
            "collected_at",
            "bytes_available",
            "bytes_total",
            "queue_depth",
            "read_latency",
            "write_latency",
        ];
        let values: &[&dyn ::core::fmt::Debug] = &[
            &self.server_id,
            &self.granularity,
            &self.mountpoint,
            &self.collected_at,
            &self.bytes_available,
            &self.bytes_total,
            &self.queue_depth,
            &self.read_latency,
            &&self.write_latency,
        ];
        ::core::fmt::Formatter::debug_struct_fields_finish(f, "Filter", names, values)
    }
}
#[automatically_derived]
impl ::core::default::Default for Filter {
    #[inline]
    fn default() -> Filter {
        Filter {
            server_id: ::core::default::Default::default(),
            granularity: ::core::default::Default::default(),
            mountpoint: ::core::default::Default::default(),
            collected_at: ::core::default::Default::default(),
            bytes_available: ::core::default::Default::default(),
            bytes_total: ::core::default::Default::default(),
            queue_depth: ::core::default::Default::default(),
            read_latency: ::core::default::Default::default(),
            write_latency: ::core::default::Default::default(),
        }
    }
}
#[doc(hidden)]
#[allow(
    non_upper_case_globals,
    unused_attributes,
    unused_qualifications,
    clippy::absolute_paths,
)]
const _: () = {
    #[allow(unused_extern_crates, clippy::useless_attribute)]
    extern crate serde as _serde;
    #[automatically_derived]
    impl<'de> _serde::Deserialize<'de> for Filter {
        fn deserialize<__D>(
            __deserializer: __D,
        ) -> _serde::__private228::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>,
        {
            #[allow(non_camel_case_types)]
            #[doc(hidden)]
            enum __Field {
                __field0,
                __field1,
                __field2,
                __field3,
                __field4,
                __field5,
                __field6,
                __field7,
                __field8,
            }
            #[doc(hidden)]
            struct __FieldVisitor;
            #[automatically_derived]
            impl<'de> _serde::de::Visitor<'de> for __FieldVisitor {
                type Value = __Field;
                fn expecting(
                    &self,
                    __formatter: &mut _serde::__private228::Formatter,
                ) -> _serde::__private228::fmt::Result {
                    _serde::__private228::Formatter::write_str(
                        __formatter,
                        "field identifier",
                    )
                }
                fn visit_u64<__E>(
                    self,
                    __value: u64,
                ) -> _serde::__private228::Result<Self::Value, __E>
                where
                    __E: _serde::de::Error,
                {
                    match __value {
                        0u64 => _serde::__private228::Ok(__Field::__field0),
                        1u64 => _serde::__private228::Ok(__Field::__field1),
                        2u64 => _serde::__private228::Ok(__Field::__field2),
                        3u64 => _serde::__private228::Ok(__Field::__field3),
                        4u64 => _serde::__private228::Ok(__Field::__field4),
                        5u64 => _serde::__private228::Ok(__Field::__field5),
                        6u64 => _serde::__private228::Ok(__Field::__field6),
                        7u64 => _serde::__private228::Ok(__Field::__field7),
                        8u64 => _serde::__private228::Ok(__Field::__field8),
                        _ => {
                            _serde::__private228::Err(
                                _serde::de::Error::invalid_value(
                                    _serde::de::Unexpected::Unsigned(__value),
                                    &"field index 0 <= i < 9",
                                ),
                            )
                        }
                    }
                }
                fn visit_str<__E>(
                    self,
                    __value: &str,
                ) -> _serde::__private228::Result<Self::Value, __E>
                where
                    __E: _serde::de::Error,
                {
                    match __value {
                        "server_id" => _serde::__private228::Ok(__Field::__field0),
                        "granularity" => _serde::__private228::Ok(__Field::__field1),
                        "mountpoint" => _serde::__private228::Ok(__Field::__field2),
                        "collected_at" => _serde::__private228::Ok(__Field::__field3),
                        "bytes_available" => _serde::__private228::Ok(__Field::__field4),
                        "bytes_total" => _serde::__private228::Ok(__Field::__field5),
                        "queue_depth" => _serde::__private228::Ok(__Field::__field6),
                        "read_latency" => _serde::__private228::Ok(__Field::__field7),
                        "write_latency" => _serde::__private228::Ok(__Field::__field8),
                        _ => {
                            _serde::__private228::Err(
                                _serde::de::Error::unknown_field(__value, FIELDS),
                            )
                        }
                    }
                }
                fn visit_bytes<__E>(
                    self,
                    __value: &[u8],
                ) -> _serde::__private228::Result<Self::Value, __E>
                where
                    __E: _serde::de::Error,
                {
                    match __value {
                        b"server_id" => _serde::__private228::Ok(__Field::__field0),
                        b"granularity" => _serde::__private228::Ok(__Field::__field1),
                        b"mountpoint" => _serde::__private228::Ok(__Field::__field2),
                        b"collected_at" => _serde::__private228::Ok(__Field::__field3),
                        b"bytes_available" => _serde::__private228::Ok(__Field::__field4),
                        b"bytes_total" => _serde::__private228::Ok(__Field::__field5),
                        b"queue_depth" => _serde::__private228::Ok(__Field::__field6),
                        b"read_latency" => _serde::__private228::Ok(__Field::__field7),
                        b"write_latency" => _serde::__private228::Ok(__Field::__field8),
                        _ => {
                            let __value = &_serde::__private228::from_utf8_lossy(
                                __value,
                            );
                            _serde::__private228::Err(
                                _serde::de::Error::unknown_field(__value, FIELDS),
                            )
                        }
                    }
                }
            }
            #[automatically_derived]
            impl<'de> _serde::Deserialize<'de> for __Field {
                #[inline]
                fn deserialize<__D>(
                    __deserializer: __D,
                ) -> _serde::__private228::Result<Self, __D::Error>
                where
                    __D: _serde::Deserializer<'de>,
                {
                    _serde::Deserializer::deserialize_identifier(
                        __deserializer,
                        __FieldVisitor,
                    )
                }
            }
            #[doc(hidden)]
            struct __Visitor<'de> {
                marker: _serde::__private228::PhantomData<Filter>,
                lifetime: _serde::__private228::PhantomData<&'de ()>,
            }
            #[automatically_derived]
            impl<'de> _serde::de::Visitor<'de> for __Visitor<'de> {
                type Value = Filter;
                fn expecting(
                    &self,
                    __formatter: &mut _serde::__private228::Formatter,
                ) -> _serde::__private228::fmt::Result {
                    _serde::__private228::Formatter::write_str(
                        __formatter,
                        "struct Filter",
                    )
                }
                #[inline]
                fn visit_seq<__A>(
                    self,
                    mut __seq: __A,
                ) -> _serde::__private228::Result<Self::Value, __A::Error>
                where
                    __A: _serde::de::SeqAccess<'de>,
                {
                    let __field0 = match {
                        #[doc(hidden)]
                        struct __DeserializeWith<'de> {
                            value: Vec<Uuid>,
                            phantom: _serde::__private228::PhantomData<Filter>,
                            lifetime: _serde::__private228::PhantomData<&'de ()>,
                        }
                        #[automatically_derived]
                        impl<'de> _serde::Deserialize<'de> for __DeserializeWith<'de> {
                            fn deserialize<__D>(
                                __deserializer: __D,
                            ) -> _serde::__private228::Result<Self, __D::Error>
                            where
                                __D: _serde::Deserializer<'de>,
                            {
                                _serde::__private228::Ok(__DeserializeWith {
                                    value: ::serde_with::As::<
                                        serde_with::DefaultOnNull<
                                            serde_with::OneOrMany<::serde_with::Same>,
                                        >,
                                    >::deserialize(__deserializer)?,
                                    phantom: _serde::__private228::PhantomData,
                                    lifetime: _serde::__private228::PhantomData,
                                })
                            }
                        }
                        _serde::__private228::Option::map(
                            _serde::de::SeqAccess::next_element::<
                                __DeserializeWith<'de>,
                            >(&mut __seq)?,
                            |__wrap| __wrap.value,
                        )
                    } {
                        _serde::__private228::Some(__value) => __value,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    let __field1 = match {
                        #[doc(hidden)]
                        struct __DeserializeWith<'de> {
                            value: Vec<i32>,
                            phantom: _serde::__private228::PhantomData<Filter>,
                            lifetime: _serde::__private228::PhantomData<&'de ()>,
                        }
                        #[automatically_derived]
                        impl<'de> _serde::Deserialize<'de> for __DeserializeWith<'de> {
                            fn deserialize<__D>(
                                __deserializer: __D,
                            ) -> _serde::__private228::Result<Self, __D::Error>
                            where
                                __D: _serde::Deserializer<'de>,
                            {
                                _serde::__private228::Ok(__DeserializeWith {
                                    value: ::serde_with::As::<
                                        serde_with::DefaultOnNull<
                                            serde_with::OneOrMany<::serde_with::Same>,
                                        >,
                                    >::deserialize(__deserializer)?,
                                    phantom: _serde::__private228::PhantomData,
                                    lifetime: _serde::__private228::PhantomData,
                                })
                            }
                        }
                        _serde::__private228::Option::map(
                            _serde::de::SeqAccess::next_element::<
                                __DeserializeWith<'de>,
                            >(&mut __seq)?,
                            |__wrap| __wrap.value,
                        )
                    } {
                        _serde::__private228::Some(__value) => __value,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    let __field2 = match {
                        #[doc(hidden)]
                        struct __DeserializeWith<'de> {
                            value: Vec<String>,
                            phantom: _serde::__private228::PhantomData<Filter>,
                            lifetime: _serde::__private228::PhantomData<&'de ()>,
                        }
                        #[automatically_derived]
                        impl<'de> _serde::Deserialize<'de> for __DeserializeWith<'de> {
                            fn deserialize<__D>(
                                __deserializer: __D,
                            ) -> _serde::__private228::Result<Self, __D::Error>
                            where
                                __D: _serde::Deserializer<'de>,
                            {
                                _serde::__private228::Ok(__DeserializeWith {
                                    value: ::serde_with::As::<
                                        serde_with::DefaultOnNull<
                                            serde_with::OneOrMany<::serde_with::Same>,
                                        >,
                                    >::deserialize(__deserializer)?,
                                    phantom: _serde::__private228::PhantomData,
                                    lifetime: _serde::__private228::PhantomData,
                                })
                            }
                        }
                        _serde::__private228::Option::map(
                            _serde::de::SeqAccess::next_element::<
                                __DeserializeWith<'de>,
                            >(&mut __seq)?,
                            |__wrap| __wrap.value,
                        )
                    } {
                        _serde::__private228::Some(__value) => __value,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    let __field3 = match {
                        #[doc(hidden)]
                        struct __DeserializeWith<'de> {
                            value: Option<std::ops::RangeInclusive<DateTime<Utc>>>,
                            phantom: _serde::__private228::PhantomData<Filter>,
                            lifetime: _serde::__private228::PhantomData<&'de ()>,
                        }
                        #[automatically_derived]
                        impl<'de> _serde::Deserialize<'de> for __DeserializeWith<'de> {
                            fn deserialize<__D>(
                                __deserializer: __D,
                            ) -> _serde::__private228::Result<Self, __D::Error>
                            where
                                __D: _serde::Deserializer<'de>,
                            {
                                _serde::__private228::Ok(__DeserializeWith {
                                    value: deserialize_time_range(__deserializer)?,
                                    phantom: _serde::__private228::PhantomData,
                                    lifetime: _serde::__private228::PhantomData,
                                })
                            }
                        }
                        _serde::__private228::Option::map(
                            _serde::de::SeqAccess::next_element::<
                                __DeserializeWith<'de>,
                            >(&mut __seq)?,
                            |__wrap| __wrap.value,
                        )
                    } {
                        _serde::__private228::Some(__value) => __value,
                        _serde::__private228::None => {
                            return _serde::__private228::Err(
                                _serde::de::Error::invalid_length(
                                    3usize,
                                    &"struct Filter with 9 elements",
                                ),
                            );
                        }
                    };
                    let __field4 = match {
                        #[doc(hidden)]
                        struct __DeserializeWith<'de> {
                            value: Vec<i64>,
                            phantom: _serde::__private228::PhantomData<Filter>,
                            lifetime: _serde::__private228::PhantomData<&'de ()>,
                        }
                        #[automatically_derived]
                        impl<'de> _serde::Deserialize<'de> for __DeserializeWith<'de> {
                            fn deserialize<__D>(
                                __deserializer: __D,
                            ) -> _serde::__private228::Result<Self, __D::Error>
                            where
                                __D: _serde::Deserializer<'de>,
                            {
                                _serde::__private228::Ok(__DeserializeWith {
                                    value: ::serde_with::As::<
                                        serde_with::DefaultOnNull<
                                            serde_with::OneOrMany<::serde_with::Same>,
                                        >,
                                    >::deserialize(__deserializer)?,
                                    phantom: _serde::__private228::PhantomData,
                                    lifetime: _serde::__private228::PhantomData,
                                })
                            }
                        }
                        _serde::__private228::Option::map(
                            _serde::de::SeqAccess::next_element::<
                                __DeserializeWith<'de>,
                            >(&mut __seq)?,
                            |__wrap| __wrap.value,
                        )
                    } {
                        _serde::__private228::Some(__value) => __value,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    let __field5 = match {
                        #[doc(hidden)]
                        struct __DeserializeWith<'de> {
                            value: Vec<i64>,
                            phantom: _serde::__private228::PhantomData<Filter>,
                            lifetime: _serde::__private228::PhantomData<&'de ()>,
                        }
                        #[automatically_derived]
                        impl<'de> _serde::Deserialize<'de> for __DeserializeWith<'de> {
                            fn deserialize<__D>(
                                __deserializer: __D,
                            ) -> _serde::__private228::Result<Self, __D::Error>
                            where
                                __D: _serde::Deserializer<'de>,
                            {
                                _serde::__private228::Ok(__DeserializeWith {
                                    value: ::serde_with::As::<
                                        serde_with::DefaultOnNull<
                                            serde_with::OneOrMany<::serde_with::Same>,
                                        >,
                                    >::deserialize(__deserializer)?,
                                    phantom: _serde::__private228::PhantomData,
                                    lifetime: _serde::__private228::PhantomData,
                                })
                            }
                        }
                        _serde::__private228::Option::map(
                            _serde::de::SeqAccess::next_element::<
                                __DeserializeWith<'de>,
                            >(&mut __seq)?,
                            |__wrap| __wrap.value,
                        )
                    } {
                        _serde::__private228::Some(__value) => __value,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    let __field6 = match {
                        #[doc(hidden)]
                        struct __DeserializeWith<'de> {
                            value: Vec<i64>,
                            phantom: _serde::__private228::PhantomData<Filter>,
                            lifetime: _serde::__private228::PhantomData<&'de ()>,
                        }
                        #[automatically_derived]
                        impl<'de> _serde::Deserialize<'de> for __DeserializeWith<'de> {
                            fn deserialize<__D>(
                                __deserializer: __D,
                            ) -> _serde::__private228::Result<Self, __D::Error>
                            where
                                __D: _serde::Deserializer<'de>,
                            {
                                _serde::__private228::Ok(__DeserializeWith {
                                    value: ::serde_with::As::<
                                        serde_with::DefaultOnNull<
                                            serde_with::OneOrMany<::serde_with::Same>,
                                        >,
                                    >::deserialize(__deserializer)?,
                                    phantom: _serde::__private228::PhantomData,
                                    lifetime: _serde::__private228::PhantomData,
                                })
                            }
                        }
                        _serde::__private228::Option::map(
                            _serde::de::SeqAccess::next_element::<
                                __DeserializeWith<'de>,
                            >(&mut __seq)?,
                            |__wrap| __wrap.value,
                        )
                    } {
                        _serde::__private228::Some(__value) => __value,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    let __field7 = match {
                        #[doc(hidden)]
                        struct __DeserializeWith<'de> {
                            value: Vec<f64>,
                            phantom: _serde::__private228::PhantomData<Filter>,
                            lifetime: _serde::__private228::PhantomData<&'de ()>,
                        }
                        #[automatically_derived]
                        impl<'de> _serde::Deserialize<'de> for __DeserializeWith<'de> {
                            fn deserialize<__D>(
                                __deserializer: __D,
                            ) -> _serde::__private228::Result<Self, __D::Error>
                            where
                                __D: _serde::Deserializer<'de>,
                            {
                                _serde::__private228::Ok(__DeserializeWith {
                                    value: ::serde_with::As::<
                                        serde_with::DefaultOnNull<
                                            serde_with::OneOrMany<::serde_with::Same>,
                                        >,
                                    >::deserialize(__deserializer)?,
                                    phantom: _serde::__private228::PhantomData,
                                    lifetime: _serde::__private228::PhantomData,
                                })
                            }
                        }
                        _serde::__private228::Option::map(
                            _serde::de::SeqAccess::next_element::<
                                __DeserializeWith<'de>,
                            >(&mut __seq)?,
                            |__wrap| __wrap.value,
                        )
                    } {
                        _serde::__private228::Some(__value) => __value,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    let __field8 = match {
                        #[doc(hidden)]
                        struct __DeserializeWith<'de> {
                            value: Vec<f64>,
                            phantom: _serde::__private228::PhantomData<Filter>,
                            lifetime: _serde::__private228::PhantomData<&'de ()>,
                        }
                        #[automatically_derived]
                        impl<'de> _serde::Deserialize<'de> for __DeserializeWith<'de> {
                            fn deserialize<__D>(
                                __deserializer: __D,
                            ) -> _serde::__private228::Result<Self, __D::Error>
                            where
                                __D: _serde::Deserializer<'de>,
                            {
                                _serde::__private228::Ok(__DeserializeWith {
                                    value: ::serde_with::As::<
                                        serde_with::DefaultOnNull<
                                            serde_with::OneOrMany<::serde_with::Same>,
                                        >,
                                    >::deserialize(__deserializer)?,
                                    phantom: _serde::__private228::PhantomData,
                                    lifetime: _serde::__private228::PhantomData,
                                })
                            }
                        }
                        _serde::__private228::Option::map(
                            _serde::de::SeqAccess::next_element::<
                                __DeserializeWith<'de>,
                            >(&mut __seq)?,
                            |__wrap| __wrap.value,
                        )
                    } {
                        _serde::__private228::Some(__value) => __value,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    _serde::__private228::Ok(Filter {
                        server_id: __field0,
                        granularity: __field1,
                        mountpoint: __field2,
                        collected_at: __field3,
                        bytes_available: __field4,
                        bytes_total: __field5,
                        queue_depth: __field6,
                        read_latency: __field7,
                        write_latency: __field8,
                    })
                }
                #[inline]
                fn visit_map<__A>(
                    self,
                    mut __map: __A,
                ) -> _serde::__private228::Result<Self::Value, __A::Error>
                where
                    __A: _serde::de::MapAccess<'de>,
                {
                    let mut __field0: _serde::__private228::Option<Vec<Uuid>> = _serde::__private228::None;
                    let mut __field1: _serde::__private228::Option<Vec<i32>> = _serde::__private228::None;
                    let mut __field2: _serde::__private228::Option<Vec<String>> = _serde::__private228::None;
                    let mut __field3: _serde::__private228::Option<
                        Option<std::ops::RangeInclusive<DateTime<Utc>>>,
                    > = _serde::__private228::None;
                    let mut __field4: _serde::__private228::Option<Vec<i64>> = _serde::__private228::None;
                    let mut __field5: _serde::__private228::Option<Vec<i64>> = _serde::__private228::None;
                    let mut __field6: _serde::__private228::Option<Vec<i64>> = _serde::__private228::None;
                    let mut __field7: _serde::__private228::Option<Vec<f64>> = _serde::__private228::None;
                    let mut __field8: _serde::__private228::Option<Vec<f64>> = _serde::__private228::None;
                    while let _serde::__private228::Some(__key) = _serde::de::MapAccess::next_key::<
                        __Field,
                    >(&mut __map)? {
                        match __key {
                            __Field::__field0 => {
                                if _serde::__private228::Option::is_some(&__field0) {
                                    return _serde::__private228::Err(
                                        <__A::Error as _serde::de::Error>::duplicate_field(
                                            "server_id",
                                        ),
                                    );
                                }
                                __field0 = _serde::__private228::Some({
                                    #[doc(hidden)]
                                    struct __DeserializeWith<'de> {
                                        value: Vec<Uuid>,
                                        phantom: _serde::__private228::PhantomData<Filter>,
                                        lifetime: _serde::__private228::PhantomData<&'de ()>,
                                    }
                                    #[automatically_derived]
                                    impl<'de> _serde::Deserialize<'de>
                                    for __DeserializeWith<'de> {
                                        fn deserialize<__D>(
                                            __deserializer: __D,
                                        ) -> _serde::__private228::Result<Self, __D::Error>
                                        where
                                            __D: _serde::Deserializer<'de>,
                                        {
                                            _serde::__private228::Ok(__DeserializeWith {
                                                value: ::serde_with::As::<
                                                    serde_with::DefaultOnNull<
                                                        serde_with::OneOrMany<::serde_with::Same>,
                                                    >,
                                                >::deserialize(__deserializer)?,
                                                phantom: _serde::__private228::PhantomData,
                                                lifetime: _serde::__private228::PhantomData,
                                            })
                                        }
                                    }
                                    match _serde::de::MapAccess::next_value::<
                                        __DeserializeWith<'de>,
                                    >(&mut __map) {
                                        _serde::__private228::Ok(__wrapper) => __wrapper.value,
                                        _serde::__private228::Err(__err) => {
                                            return _serde::__private228::Err(__err);
                                        }
                                    }
                                });
                            }
                            __Field::__field1 => {
                                if _serde::__private228::Option::is_some(&__field1) {
                                    return _serde::__private228::Err(
                                        <__A::Error as _serde::de::Error>::duplicate_field(
                                            "granularity",
                                        ),
                                    );
                                }
                                __field1 = _serde::__private228::Some({
                                    #[doc(hidden)]
                                    struct __DeserializeWith<'de> {
                                        value: Vec<i32>,
                                        phantom: _serde::__private228::PhantomData<Filter>,
                                        lifetime: _serde::__private228::PhantomData<&'de ()>,
                                    }
                                    #[automatically_derived]
                                    impl<'de> _serde::Deserialize<'de>
                                    for __DeserializeWith<'de> {
                                        fn deserialize<__D>(
                                            __deserializer: __D,
                                        ) -> _serde::__private228::Result<Self, __D::Error>
                                        where
                                            __D: _serde::Deserializer<'de>,
                                        {
                                            _serde::__private228::Ok(__DeserializeWith {
                                                value: ::serde_with::As::<
                                                    serde_with::DefaultOnNull<
                                                        serde_with::OneOrMany<::serde_with::Same>,
                                                    >,
                                                >::deserialize(__deserializer)?,
                                                phantom: _serde::__private228::PhantomData,
                                                lifetime: _serde::__private228::PhantomData,
                                            })
                                        }
                                    }
                                    match _serde::de::MapAccess::next_value::<
                                        __DeserializeWith<'de>,
                                    >(&mut __map) {
                                        _serde::__private228::Ok(__wrapper) => __wrapper.value,
                                        _serde::__private228::Err(__err) => {
                                            return _serde::__private228::Err(__err);
                                        }
                                    }
                                });
                            }
                            __Field::__field2 => {
                                if _serde::__private228::Option::is_some(&__field2) {
                                    return _serde::__private228::Err(
                                        <__A::Error as _serde::de::Error>::duplicate_field(
                                            "mountpoint",
                                        ),
                                    );
                                }
                                __field2 = _serde::__private228::Some({
                                    #[doc(hidden)]
                                    struct __DeserializeWith<'de> {
                                        value: Vec<String>,
                                        phantom: _serde::__private228::PhantomData<Filter>,
                                        lifetime: _serde::__private228::PhantomData<&'de ()>,
                                    }
                                    #[automatically_derived]
                                    impl<'de> _serde::Deserialize<'de>
                                    for __DeserializeWith<'de> {
                                        fn deserialize<__D>(
                                            __deserializer: __D,
                                        ) -> _serde::__private228::Result<Self, __D::Error>
                                        where
                                            __D: _serde::Deserializer<'de>,
                                        {
                                            _serde::__private228::Ok(__DeserializeWith {
                                                value: ::serde_with::As::<
                                                    serde_with::DefaultOnNull<
                                                        serde_with::OneOrMany<::serde_with::Same>,
                                                    >,
                                                >::deserialize(__deserializer)?,
                                                phantom: _serde::__private228::PhantomData,
                                                lifetime: _serde::__private228::PhantomData,
                                            })
                                        }
                                    }
                                    match _serde::de::MapAccess::next_value::<
                                        __DeserializeWith<'de>,
                                    >(&mut __map) {
                                        _serde::__private228::Ok(__wrapper) => __wrapper.value,
                                        _serde::__private228::Err(__err) => {
                                            return _serde::__private228::Err(__err);
                                        }
                                    }
                                });
                            }
                            __Field::__field3 => {
                                if _serde::__private228::Option::is_some(&__field3) {
                                    return _serde::__private228::Err(
                                        <__A::Error as _serde::de::Error>::duplicate_field(
                                            "collected_at",
                                        ),
                                    );
                                }
                                __field3 = _serde::__private228::Some({
                                    #[doc(hidden)]
                                    struct __DeserializeWith<'de> {
                                        value: Option<std::ops::RangeInclusive<DateTime<Utc>>>,
                                        phantom: _serde::__private228::PhantomData<Filter>,
                                        lifetime: _serde::__private228::PhantomData<&'de ()>,
                                    }
                                    #[automatically_derived]
                                    impl<'de> _serde::Deserialize<'de>
                                    for __DeserializeWith<'de> {
                                        fn deserialize<__D>(
                                            __deserializer: __D,
                                        ) -> _serde::__private228::Result<Self, __D::Error>
                                        where
                                            __D: _serde::Deserializer<'de>,
                                        {
                                            _serde::__private228::Ok(__DeserializeWith {
                                                value: deserialize_time_range(__deserializer)?,
                                                phantom: _serde::__private228::PhantomData,
                                                lifetime: _serde::__private228::PhantomData,
                                            })
                                        }
                                    }
                                    match _serde::de::MapAccess::next_value::<
                                        __DeserializeWith<'de>,
                                    >(&mut __map) {
                                        _serde::__private228::Ok(__wrapper) => __wrapper.value,
                                        _serde::__private228::Err(__err) => {
                                            return _serde::__private228::Err(__err);
                                        }
                                    }
                                });
                            }
                            __Field::__field4 => {
                                if _serde::__private228::Option::is_some(&__field4) {
                                    return _serde::__private228::Err(
                                        <__A::Error as _serde::de::Error>::duplicate_field(
                                            "bytes_available",
                                        ),
                                    );
                                }
                                __field4 = _serde::__private228::Some({
                                    #[doc(hidden)]
                                    struct __DeserializeWith<'de> {
                                        value: Vec<i64>,
                                        phantom: _serde::__private228::PhantomData<Filter>,
                                        lifetime: _serde::__private228::PhantomData<&'de ()>,
                                    }
                                    #[automatically_derived]
                                    impl<'de> _serde::Deserialize<'de>
                                    for __DeserializeWith<'de> {
                                        fn deserialize<__D>(
                                            __deserializer: __D,
                                        ) -> _serde::__private228::Result<Self, __D::Error>
                                        where
                                            __D: _serde::Deserializer<'de>,
                                        {
                                            _serde::__private228::Ok(__DeserializeWith {
                                                value: ::serde_with::As::<
                                                    serde_with::DefaultOnNull<
                                                        serde_with::OneOrMany<::serde_with::Same>,
                                                    >,
                                                >::deserialize(__deserializer)?,
                                                phantom: _serde::__private228::PhantomData,
                                                lifetime: _serde::__private228::PhantomData,
                                            })
                                        }
                                    }
                                    match _serde::de::MapAccess::next_value::<
                                        __DeserializeWith<'de>,
                                    >(&mut __map) {
                                        _serde::__private228::Ok(__wrapper) => __wrapper.value,
                                        _serde::__private228::Err(__err) => {
                                            return _serde::__private228::Err(__err);
                                        }
                                    }
                                });
                            }
                            __Field::__field5 => {
                                if _serde::__private228::Option::is_some(&__field5) {
                                    return _serde::__private228::Err(
                                        <__A::Error as _serde::de::Error>::duplicate_field(
                                            "bytes_total",
                                        ),
                                    );
                                }
                                __field5 = _serde::__private228::Some({
                                    #[doc(hidden)]
                                    struct __DeserializeWith<'de> {
                                        value: Vec<i64>,
                                        phantom: _serde::__private228::PhantomData<Filter>,
                                        lifetime: _serde::__private228::PhantomData<&'de ()>,
                                    }
                                    #[automatically_derived]
                                    impl<'de> _serde::Deserialize<'de>
                                    for __DeserializeWith<'de> {
                                        fn deserialize<__D>(
                                            __deserializer: __D,
                                        ) -> _serde::__private228::Result<Self, __D::Error>
                                        where
                                            __D: _serde::Deserializer<'de>,
                                        {
                                            _serde::__private228::Ok(__DeserializeWith {
                                                value: ::serde_with::As::<
                                                    serde_with::DefaultOnNull<
                                                        serde_with::OneOrMany<::serde_with::Same>,
                                                    >,
                                                >::deserialize(__deserializer)?,
                                                phantom: _serde::__private228::PhantomData,
                                                lifetime: _serde::__private228::PhantomData,
                                            })
                                        }
                                    }
                                    match _serde::de::MapAccess::next_value::<
                                        __DeserializeWith<'de>,
                                    >(&mut __map) {
                                        _serde::__private228::Ok(__wrapper) => __wrapper.value,
                                        _serde::__private228::Err(__err) => {
                                            return _serde::__private228::Err(__err);
                                        }
                                    }
                                });
                            }
                            __Field::__field6 => {
                                if _serde::__private228::Option::is_some(&__field6) {
                                    return _serde::__private228::Err(
                                        <__A::Error as _serde::de::Error>::duplicate_field(
                                            "queue_depth",
                                        ),
                                    );
                                }
                                __field6 = _serde::__private228::Some({
                                    #[doc(hidden)]
                                    struct __DeserializeWith<'de> {
                                        value: Vec<i64>,
                                        phantom: _serde::__private228::PhantomData<Filter>,
                                        lifetime: _serde::__private228::PhantomData<&'de ()>,
                                    }
                                    #[automatically_derived]
                                    impl<'de> _serde::Deserialize<'de>
                                    for __DeserializeWith<'de> {
                                        fn deserialize<__D>(
                                            __deserializer: __D,
                                        ) -> _serde::__private228::Result<Self, __D::Error>
                                        where
                                            __D: _serde::Deserializer<'de>,
                                        {
                                            _serde::__private228::Ok(__DeserializeWith {
                                                value: ::serde_with::As::<
                                                    serde_with::DefaultOnNull<
                                                        serde_with::OneOrMany<::serde_with::Same>,
                                                    >,
                                                >::deserialize(__deserializer)?,
                                                phantom: _serde::__private228::PhantomData,
                                                lifetime: _serde::__private228::PhantomData,
                                            })
                                        }
                                    }
                                    match _serde::de::MapAccess::next_value::<
                                        __DeserializeWith<'de>,
                                    >(&mut __map) {
                                        _serde::__private228::Ok(__wrapper) => __wrapper.value,
                                        _serde::__private228::Err(__err) => {
                                            return _serde::__private228::Err(__err);
                                        }
                                    }
                                });
                            }
                            __Field::__field7 => {
                                if _serde::__private228::Option::is_some(&__field7) {
                                    return _serde::__private228::Err(
                                        <__A::Error as _serde::de::Error>::duplicate_field(
                                            "read_latency",
                                        ),
                                    );
                                }
                                __field7 = _serde::__private228::Some({
                                    #[doc(hidden)]
                                    struct __DeserializeWith<'de> {
                                        value: Vec<f64>,
                                        phantom: _serde::__private228::PhantomData<Filter>,
                                        lifetime: _serde::__private228::PhantomData<&'de ()>,
                                    }
                                    #[automatically_derived]
                                    impl<'de> _serde::Deserialize<'de>
                                    for __DeserializeWith<'de> {
                                        fn deserialize<__D>(
                                            __deserializer: __D,
                                        ) -> _serde::__private228::Result<Self, __D::Error>
                                        where
                                            __D: _serde::Deserializer<'de>,
                                        {
                                            _serde::__private228::Ok(__DeserializeWith {
                                                value: ::serde_with::As::<
                                                    serde_with::DefaultOnNull<
                                                        serde_with::OneOrMany<::serde_with::Same>,
                                                    >,
                                                >::deserialize(__deserializer)?,
                                                phantom: _serde::__private228::PhantomData,
                                                lifetime: _serde::__private228::PhantomData,
                                            })
                                        }
                                    }
                                    match _serde::de::MapAccess::next_value::<
                                        __DeserializeWith<'de>,
                                    >(&mut __map) {
                                        _serde::__private228::Ok(__wrapper) => __wrapper.value,
                                        _serde::__private228::Err(__err) => {
                                            return _serde::__private228::Err(__err);
                                        }
                                    }
                                });
                            }
                            __Field::__field8 => {
                                if _serde::__private228::Option::is_some(&__field8) {
                                    return _serde::__private228::Err(
                                        <__A::Error as _serde::de::Error>::duplicate_field(
                                            "write_latency",
                                        ),
                                    );
                                }
                                __field8 = _serde::__private228::Some({
                                    #[doc(hidden)]
                                    struct __DeserializeWith<'de> {
                                        value: Vec<f64>,
                                        phantom: _serde::__private228::PhantomData<Filter>,
                                        lifetime: _serde::__private228::PhantomData<&'de ()>,
                                    }
                                    #[automatically_derived]
                                    impl<'de> _serde::Deserialize<'de>
                                    for __DeserializeWith<'de> {
                                        fn deserialize<__D>(
                                            __deserializer: __D,
                                        ) -> _serde::__private228::Result<Self, __D::Error>
                                        where
                                            __D: _serde::Deserializer<'de>,
                                        {
                                            _serde::__private228::Ok(__DeserializeWith {
                                                value: ::serde_with::As::<
                                                    serde_with::DefaultOnNull<
                                                        serde_with::OneOrMany<::serde_with::Same>,
                                                    >,
                                                >::deserialize(__deserializer)?,
                                                phantom: _serde::__private228::PhantomData,
                                                lifetime: _serde::__private228::PhantomData,
                                            })
                                        }
                                    }
                                    match _serde::de::MapAccess::next_value::<
                                        __DeserializeWith<'de>,
                                    >(&mut __map) {
                                        _serde::__private228::Ok(__wrapper) => __wrapper.value,
                                        _serde::__private228::Err(__err) => {
                                            return _serde::__private228::Err(__err);
                                        }
                                    }
                                });
                            }
                        }
                    }
                    let __field0 = match __field0 {
                        _serde::__private228::Some(__field0) => __field0,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    let __field1 = match __field1 {
                        _serde::__private228::Some(__field1) => __field1,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    let __field2 = match __field2 {
                        _serde::__private228::Some(__field2) => __field2,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    let __field3 = match __field3 {
                        _serde::__private228::Some(__field3) => __field3,
                        _serde::__private228::None => {
                            return _serde::__private228::Err(
                                <__A::Error as _serde::de::Error>::missing_field(
                                    "collected_at",
                                ),
                            );
                        }
                    };
                    let __field4 = match __field4 {
                        _serde::__private228::Some(__field4) => __field4,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    let __field5 = match __field5 {
                        _serde::__private228::Some(__field5) => __field5,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    let __field6 = match __field6 {
                        _serde::__private228::Some(__field6) => __field6,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    let __field7 = match __field7 {
                        _serde::__private228::Some(__field7) => __field7,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    let __field8 = match __field8 {
                        _serde::__private228::Some(__field8) => __field8,
                        _serde::__private228::None => {
                            _serde::__private228::Default::default()
                        }
                    };
                    _serde::__private228::Ok(Filter {
                        server_id: __field0,
                        granularity: __field1,
                        mountpoint: __field2,
                        collected_at: __field3,
                        bytes_available: __field4,
                        bytes_total: __field5,
                        queue_depth: __field6,
                        read_latency: __field7,
                        write_latency: __field8,
                    })
                }
            }
            #[doc(hidden)]
            const FIELDS: &'static [&'static str] = &[
                "server_id",
                "granularity",
                "mountpoint",
                "collected_at",
                "bytes_available",
                "bytes_total",
                "queue_depth",
                "read_latency",
                "write_latency",
            ];
            _serde::Deserializer::deserialize_struct(
                __deserializer,
                "Filter",
                FIELDS,
                __Visitor {
                    marker: _serde::__private228::PhantomData::<Filter>,
                    lifetime: _serde::__private228::PhantomData,
                },
            )
        }
    }
};
#[automatically_derived]
impl ::core::clone::Clone for Filter {
    #[inline]
    fn clone(&self) -> Filter {
        Filter {
            server_id: ::core::clone::Clone::clone(&self.server_id),
            granularity: ::core::clone::Clone::clone(&self.granularity),
            mountpoint: ::core::clone::Clone::clone(&self.mountpoint),
            collected_at: ::core::clone::Clone::clone(&self.collected_at),
            bytes_available: ::core::clone::Clone::clone(&self.bytes_available),
            bytes_total: ::core::clone::Clone::clone(&self.bytes_total),
            queue_depth: ::core::clone::Clone::clone(&self.queue_depth),
            read_latency: ::core::clone::Clone::clone(&self.read_latency),
            write_latency: ::core::clone::Clone::clone(&self.write_latency),
        }
    }
}
#[automatically_derived]
impl ::core::marker::StructuralPartialEq for Filter {}
#[automatically_derived]
impl ::core::cmp::PartialEq for Filter {
    #[inline]
    fn eq(&self, other: &Filter) -> bool {
        self.server_id == other.server_id && self.granularity == other.granularity
            && self.mountpoint == other.mountpoint
            && self.collected_at == other.collected_at
            && self.bytes_available == other.bytes_available
            && self.bytes_total == other.bytes_total
            && self.queue_depth == other.queue_depth
            && self.read_latency == other.read_latency
            && self.write_latency == other.write_latency
    }
}
impl Filter {
    /// Builds new filter with the required fields defined by `group_by` and `timestamp`
    pub fn new(
        server_id: &[Uuid],
        granularity: &[i32],
        mountpoint: &[String],
        collected_at: std::ops::RangeInclusive<DateTime<Utc>>,
    ) -> Self {
        Self {
            server_id: server_id.into(),
            granularity: granularity.into(),
            mountpoint: mountpoint.into(),
            collected_at: Some(collected_at),
            ..Self::default()
        }
    }
    fn matches(&self, row: &SystemStorageStat) -> bool {
        (self.server_id.is_empty() || self.server_id.contains(&row.server_id))
            && (self.granularity.is_empty()
                || self.granularity.contains(&row.granularity))
            && (self.mountpoint.is_empty() || self.mountpoint.contains(&row.mountpoint))
            && self.collected_at.as_ref().map(|t| t.contains(&row.collected_at))
                != Some(false)
            && (self.bytes_available.is_empty()
                || self.bytes_available.contains(&row.bytes_available))
            && (self.bytes_total.is_empty()
                || self.bytes_total.contains(&row.bytes_total))
            && (self.queue_depth.is_empty()
                || self.queue_depth.contains(&row.queue_depth))
            && (self.read_latency.is_empty()
                || self.read_latency.contains(&row.read_latency))
            && (self.write_latency.is_empty()
                || self.write_latency.contains(&row.write_latency))
    }
    /// Convenience function to unwrap the timestamp range lower and upper bounds
    pub fn range_bounds(&self) -> anyhow::Result<(DateTime<Utc>, DateTime<Utc>)> {
        use anyhow::Context;
        let timestamp = self.collected_at.clone().context("no timestamp")?;
        Ok((*timestamp.start(), *timestamp.end()))
    }
    /// Convenience function to return the amount of time the filter covers
    pub fn range_duration(&self) -> anyhow::Result<chrono::Duration> {
        let (start, end) = self.range_bounds()?;
        Ok(end - start)
    }
    /// Shifts the filtered time range. This for example makes it easier
    /// to perform two queries: once for "today", and one for "today, 7 days ago".
    /// In that example the second query would do `filter.shift(Duration::days(-7))`
    pub fn range_shift(&mut self, duration: chrono::Duration) -> anyhow::Result<()> {
        use std::ops::Add;
        let (start, end) = self.range_bounds()?;
        self.collected_at = Some(start.add(duration)..=end.add(duration));
        Ok(())
    }
    /// Postgres doesn't support nanosecond precision and nor does MacOS, so this
    /// truncates nanosecond precision for timestamp comparisons
    fn range_truncate(&mut self) -> anyhow::Result<()> {
        let (start, end) = self.range_bounds()?;
        self.collected_at = Some(
            Self::truncate_nanos(start)?..=Self::truncate_nanos(end)?,
        );
        Ok(())
    }
    fn truncate_nanos(time: DateTime<Utc>) -> anyhow::Result<DateTime<Utc>> {
        use anyhow::Context;
        Ok(
            chrono::DateTime::from_timestamp_micros(time.timestamp_micros())
                .context("out of range")?,
        )
    }
}
/// Generated by pco_store to choose which fields to decompress when loading [SystemStorageStat]
pub struct Fields {
    server_id: bool,
    granularity: bool,
    mountpoint: bool,
    collected_at: bool,
    bytes_available: bool,
    bytes_total: bool,
    queue_depth: bool,
    read_latency: bool,
    write_latency: bool,
}
#[automatically_derived]
#[doc(hidden)]
unsafe impl ::core::clone::TrivialClone for Fields {}
#[automatically_derived]
impl ::core::clone::Clone for Fields {
    #[inline]
    fn clone(&self) -> Fields {
        let _: ::core::clone::AssertParamIsClone<bool>;
        *self
    }
}
#[automatically_derived]
impl ::core::marker::Copy for Fields {}
#[automatically_derived]
impl ::core::fmt::Debug for Fields {
    #[inline]
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        let names: &'static _ = &[
            "server_id",
            "granularity",
            "mountpoint",
            "collected_at",
            "bytes_available",
            "bytes_total",
            "queue_depth",
            "read_latency",
            "write_latency",
        ];
        let values: &[&dyn ::core::fmt::Debug] = &[
            &self.server_id,
            &self.granularity,
            &self.mountpoint,
            &self.collected_at,
            &self.bytes_available,
            &self.bytes_total,
            &self.queue_depth,
            &self.read_latency,
            &&self.write_latency,
        ];
        ::core::fmt::Formatter::debug_struct_fields_finish(f, "Fields", names, values)
    }
}
#[automatically_derived]
impl ::core::marker::StructuralPartialEq for Fields {}
#[automatically_derived]
impl ::core::cmp::PartialEq for Fields {
    #[inline]
    fn eq(&self, other: &Fields) -> bool {
        self.server_id == other.server_id && self.granularity == other.granularity
            && self.mountpoint == other.mountpoint
            && self.collected_at == other.collected_at
            && self.bytes_available == other.bytes_available
            && self.bytes_total == other.bytes_total
            && self.queue_depth == other.queue_depth
            && self.read_latency == other.read_latency
            && self.write_latency == other.write_latency
    }
}
impl Fields {
    pub fn new(fields: &[&str]) -> anyhow::Result<Self> {
        fields.try_into().map_err(|e| anyhow::Error::msg(e))
    }
    pub fn required() -> Self {
        Self {
            server_id: true,
            granularity: true,
            mountpoint: true,
            collected_at: true,
            bytes_available: false,
            bytes_total: false,
            queue_depth: false,
            read_latency: false,
            write_latency: false,
        }
    }
    fn merge_filter(&mut self, filter: &Filter) {
        (!filter.bytes_available.is_empty()).then(|| self.bytes_available = true);
        (!filter.bytes_total.is_empty()).then(|| self.bytes_total = true);
        (!filter.queue_depth.is_empty()).then(|| self.queue_depth = true);
        (!filter.read_latency.is_empty()).then(|| self.read_latency = true);
        (!filter.write_latency.is_empty()).then(|| self.write_latency = true);
    }
    fn select(&self) -> String {
        let mut fields = Vec::new();
        self.server_id.then(|| fields.push("server_id"));
        self.granularity.then(|| fields.push("granularity"));
        self.mountpoint.then(|| fields.push("mountpoint"));
        self.collected_at.then(|| fields.push("collected_at"));
        self.bytes_available.then(|| fields.push("bytes_available"));
        self.bytes_total.then(|| fields.push("bytes_total"));
        self.queue_depth.then(|| fields.push("queue_depth"));
        self.read_latency.then(|| fields.push("read_latency"));
        self.write_latency.then(|| fields.push("write_latency"));
        fields.join(", ")
    }
    fn load_from_row(
        &self,
        row: tokio_postgres::Row,
        filter: Option<Filter>,
    ) -> anyhow::Result<CompressedSystemStorageStats> {
        let mut index = 0;
        Ok(CompressedSystemStorageStats {
            filter,
            server_id: if self.server_id {
                let v = row.get(index);
                index += 1;
                v
            } else {
                Default::default()
            },
            granularity: if self.granularity {
                let v = row.get(index);
                index += 1;
                v
            } else {
                Default::default()
            },
            mountpoint: if self.mountpoint {
                let v = row.get(index);
                index += 1;
                v
            } else {
                Default::default()
            },
            collected_at: if self.collected_at {
                let v = row.get(index);
                index += 1;
                v
            } else {
                Default::default()
            },
            bytes_available: if self.bytes_available {
                let v = row.get(index);
                index += 1;
                v
            } else {
                Default::default()
            },
            bytes_total: if self.bytes_total {
                let v = row.get(index);
                index += 1;
                v
            } else {
                Default::default()
            },
            queue_depth: if self.queue_depth {
                let v = row.get(index);
                index += 1;
                v
            } else {
                Default::default()
            },
            read_latency: if self.read_latency {
                let v = row.get(index);
                index += 1;
                v
            } else {
                Default::default()
            },
            write_latency: if self.write_latency {
                let v = row.get(index);
                index += 1;
                v
            } else {
                Default::default()
            },
        })
    }
}
impl Default for Fields {
    fn default() -> Self {
        Self {
            server_id: true,
            granularity: true,
            mountpoint: true,
            collected_at: true,
            bytes_available: true,
            bytes_total: true,
            queue_depth: true,
            read_latency: true,
            write_latency: true,
        }
    }
}
impl TryFrom<&[&str]> for Fields {
    type Error = &'static str;
    fn try_from(input: &[&str]) -> Result<Self, Self::Error> {
        let mut fields = Self::required();
        for s in input {
            match *s {
                "server_id" => fields.server_id = true,
                "granularity" => fields.granularity = true,
                "mountpoint" => fields.mountpoint = true,
                "collected_at" => fields.collected_at = true,
                "bytes_available" => fields.bytes_available = true,
                "bytes_total" => fields.bytes_total = true,
                "queue_depth" => fields.queue_depth = true,
                "read_latency" => fields.read_latency = true,
                "write_latency" => fields.write_latency = true,
                _ => return Err("unknown field"),
            }
        }
        Ok(fields)
    }
}
impl<const N: usize> TryFrom<&[&str; N]> for Fields {
    type Error = &'static str;
    fn try_from(input: &[&str; N]) -> Result<Self, Self::Error> {
        Self::try_from(&input[..])
    }
}
impl TryFrom<Vec<String>> for Fields {
    type Error = &'static str;
    fn try_from(input: Vec<String>) -> Result<Self, Self::Error> {
        let input: Vec<_> = input.iter().map(|s| s.as_str()).collect();
        Self::try_from(input.as_slice())
    }
}
impl From<()> for Fields {
    fn from(_: ()) -> Self {
        Self::default()
    }
}
impl<'de> serde::Deserialize<'de> for Fields {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        deserializer.deserialize_any(FieldsVisitor)
    }
}
struct FieldsVisitor;
impl<'de> serde::de::Visitor<'de> for FieldsVisitor {
    type Value = Fields;
    fn expecting(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
        formatter.write_str("an array of strings matching the struct fields")
    }
    fn visit_seq<A>(self, mut seq: A) -> Result<Self::Value, A::Error>
    where
        A: serde::de::SeqAccess<'de>,
    {
        let mut fields = Vec::new();
        while let Some(field) = seq.next_element()? {
            fields.push(field);
        }
        Fields::try_from(fields).map_err(serde::de::Error::custom)
    }
    fn visit_unit<E>(self) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        Ok(Fields::default())
    }
}
/// Deserializes many different time range formats:
/// - an array with two strings becomes a normal time range: ["a", "b"] -> a..=b
/// - an array with one string becomes a single-value time range: ["a"] -> a..=a
/// - a string literal becomes a single-value time range:           "a" -> a..=a
fn deserialize_time_range<'de, D>(
    deserializer: D,
) -> Result<Option<std::ops::RangeInclusive<DateTime<Utc>>>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    Ok(TimeRange::deserialize(deserializer)?.0)
}
struct TimeRange(Option<std::ops::RangeInclusive<DateTime<Utc>>>);
#[automatically_derived]
impl ::core::fmt::Debug for TimeRange {
    #[inline]
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        ::core::fmt::Formatter::debug_tuple_field1_finish(f, "TimeRange", &&self.0)
    }
}
#[automatically_derived]
impl ::core::marker::StructuralPartialEq for TimeRange {}
#[automatically_derived]
impl ::core::cmp::PartialEq for TimeRange {
    #[inline]
    fn eq(&self, other: &TimeRange) -> bool {
        self.0 == other.0
    }
}
impl<'de> serde::Deserialize<'de> for TimeRange {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        deserializer.deserialize_any(TimeRangeVisitor)
    }
}
struct TimeRangeVisitor;
impl<'de> serde::de::Visitor<'de> for TimeRangeVisitor {
    type Value = TimeRange;
    fn expecting(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
        formatter.write_str("a single time string or an array with 1-2 time strings")
    }
    fn visit_str<E>(self, value: &str) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        if value.is_empty() {
            return Ok(TimeRange(None));
        }
        match serde::Deserialize::deserialize(
            serde::de::value::StrDeserializer::<E>::new(value),
        ) {
            Ok(start) => Ok(TimeRange(Some(start..=start))),
            Err(err) => {
                Err(
                    E::custom(
                        "invalid time format: ".to_string() + err.to_string().as_str(),
                    ),
                )
            }
        }
    }
    fn visit_seq<A>(self, mut seq: A) -> Result<Self::Value, A::Error>
    where
        A: serde::de::SeqAccess<'de>,
    {
        let start = match seq.next_element::<Option<DateTime<Utc>>>()? {
            Some(Some(time)) => time,
            Some(None) | None => return Ok(TimeRange(None)),
        };
        let end = match seq.next_element::<Option<DateTime<Utc>>>()? {
            Some(Some(time)) => time,
            Some(None) | None => start,
        };
        Ok(TimeRange(Some(start..=end)))
    }
    fn visit_unit<E>(self) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        Ok(TimeRange(None))
    }
}
