use quote::quote;
use syn::{Ident, ItemStruct};

use super::{Arguments, tokens};

pub fn generate(model: ItemStruct, args: Arguments, packed_name: Ident) -> proc_macro2::TokenStream {
    let name = model.ident.clone();
    let Arguments { timestamp, group_by, .. } = args;
    let mut fields = Vec::new();
    let mut required = Vec::new();
    let mut merge_filter = Vec::new();
    let mut select = Vec::new();
    let mut load = Vec::new();
    let mut default = Vec::new();
    let mut from = Vec::new();
    for field in model.fields.iter() {
        let ident = field.ident.clone().unwrap();
        let name = format!("{ident}");
        let is_timestamp = timestamp.as_ref().map(|t| *t == ident).unwrap_or(false);
        fields.push(quote! { #ident: bool, });
        if group_by.iter().any(|i| *i == ident) || is_timestamp {
            required.push(quote! { #ident: true, });
        } else {
            required.push(quote! { #ident: false, });
            merge_filter.push(quote! {
                (!filter.#ident.is_empty()).then(|| self.#ident = true);
            });
        }
        select.push(quote! { self.#ident.then(|| fields.push(#name)); });
        load.push(quote! { #ident: if self.#ident {
                let v = row.get(index);
                index += 1;
                v
            } else {
                Default::default()
            },
        });
        default.push(quote! { #ident: true, });
        from.push(quote! { #name => fields.#ident = true, });
    }
    let fields = tokens(fields);
    let required = tokens(required);
    let merge_filter = tokens(merge_filter);
    let select = tokens(select);
    let load = tokens(load);
    let default = tokens(default);
    let from = tokens(from);
    quote! {
        #[derive(Clone, Copy, Debug, PartialEq)]
        #[doc=concat!(" Generated by pco_store to choose which fields to decompress when loading [", stringify!(#name), "]")]
        pub struct Fields {
            #fields
        }

        impl Fields {
            pub fn new(fields: &[&str]) -> anyhow::Result<Self> {
                fields.try_into().map_err(|e| anyhow::Error::msg(e))
            }

            pub fn required() -> Self {
                Self { #required }
            }

            fn merge_filter(&mut self, filter: &Filter) {
                #merge_filter
            }

            fn select(&self) -> String {
                let mut fields = Vec::new();
                #select
                fields.join(", ")
            }

            fn load_from_row(&self, row: tokio_postgres::Row, filter: Option<Filter>) -> anyhow::Result<#packed_name> {
                let mut index = 0;
                Ok(#packed_name {
                    filter,
                    #load
                })
            }
        }

        impl Default for Fields {
            fn default() -> Self {
                Self { #default }
            }
        }

        impl TryFrom<&[&str]> for Fields {
            type Error = &'static str;
            fn try_from(input: &[&str]) -> Result<Self, Self::Error> {
                let mut fields = Self::required();
                for s in input {
                    match *s {
                        #from
                        _ => return Err("unknown field"),
                    }
                }
                Ok(fields)
            }
        }

        impl<const N: usize> TryFrom<&[&str; N]> for Fields {
            type Error = &'static str;
            fn try_from(input: &[&str; N]) -> Result<Self, Self::Error> {
                Self::try_from(&input[..])
            }
        }

        impl TryFrom<Vec<String>> for Fields {
            type Error = &'static str;
            fn try_from(input: Vec<String>) -> Result<Self, Self::Error> {
                let input: Vec<_> = input.iter().map(|s| s.as_str()).collect();
                Self::try_from(input.as_slice())
            }
        }

        impl From<()> for Fields {
            fn from(_: ()) -> Self {
                Self::default()
            }
        }

        impl<'de> serde::Deserialize<'de> for Fields {
            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
            where
                D: serde::Deserializer<'de>,
            {
                deserializer.deserialize_any(FieldsVisitor)
            }
        }

        struct FieldsVisitor;
        impl<'de> serde::de::Visitor<'de> for FieldsVisitor {
            type Value = Fields;

            fn expecting(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
                formatter.write_str("an array of strings matching the struct fields")
            }

            fn visit_seq<A>(self, mut seq: A) -> Result<Self::Value, A::Error>
            where
                A: serde::de::SeqAccess<'de>,
            {
                let mut fields = Vec::new();
                while let Some(field) = seq.next_element()? {
                    fields.push(field);
                }
                Fields::try_from(fields).map_err(serde::de::Error::custom)
            }

            fn visit_unit<E>(self) -> Result<Self::Value, E>
            where
                E: serde::de::Error,
            {
                Ok(Fields::default())
            }
        }
    }
}
