use proc_macro::TokenStream;
use proc_macro2::Span;
use quote::{ToTokens, quote};
use syn::{Ident, ItemStruct, Type};

use super::deserialize_time_range::*;
use super::fields::*;
use super::filter::*;
use super::*;

mod decompress;
mod delete;
mod load;
mod store;

pub fn generate(args: Arguments, model: ItemStruct, item: proc_macro2::TokenStream) -> TokenStream {
    let Arguments { timestamp, group_by, float_round, table_name } = args.clone();
    let name = model.ident.clone();
    let packed_name = Ident::new(&format!("Compressed{}s", model.ident), Span::call_site());

    let table_name = if let Some(table_name) = table_name {
        table_name.to_string()
    } else {
        let mut table_name = String::new();
        for c in model.ident.to_string().chars() {
            if c.is_uppercase() && table_name.len() > 0 {
                table_name += "_";
            }
            table_name += &c.to_lowercase().to_string();
        }
        table_name += "s";
        table_name
    };

    // load and delete
    let mut packed_fields = vec![quote! { filter: Option<Filter>, }];
    let mut load_checks = Vec::new();
    let mut load_where = Vec::new();
    let mut load_params = Vec::new();
    let mut bind = 1;
    let mut timestamp_ty = None;
    let mut using_chrono = false;
    for field in model.fields.iter() {
        let ident = field.ident.clone().unwrap();
        let ty = field.ty.clone();
        let name = format!("{ident}");
        if group_by.iter().any(|i| *i == ident) {
            packed_fields.push(quote! { #ident: #ty, });
            load_checks.push(quote! {
                if filter.#ident.is_empty() {
                    return Err(anyhow::Error::msg(#name.to_string() + " is required"));
                }
            });
            load_where.push(format!("{ident} = ANY(${bind})"));
            bind += 1;
            load_params.push(quote! { &filter.#ident, });
        } else if timestamp.as_ref().map(|t| *t == ident).unwrap_or(false) {
            using_chrono = !ty.to_token_stream().to_string().contains("SystemTime");
            timestamp_ty = Some(ty.clone());
            packed_fields.push(quote! { #ident: Vec<u8>, });
            load_checks.push(quote! {
                if filter.#ident.is_none() {
                    return Err(anyhow::Error::msg(#name.to_string() + " is required"));
                }
                filter.range_truncate()?;
            });
            load_where.push(format!("end_at >= ${bind}"));
            bind += 1;
            load_where.push(format!("start_at <= ${bind}"));
            bind += 1;
            load_params.push(quote! {
                filter.#ident.as_ref().unwrap().start(),
                filter.#ident.as_ref().unwrap().end(),
            });
        } else {
            packed_fields.push(quote! { #ident: Vec<u8>, });
        }
    }
    let packed_fields = tokens(packed_fields);
    let load_checks = tokens(load_checks);
    let load_where = if load_where.is_empty() { "true".to_string() } else { load_where.join(" AND ") };
    let load_params = tokens(load_params);


    let filter = filter(model.clone(), args.clone(), using_chrono, &timestamp_ty);
    let fields = fields(model.clone(), args.clone(), packed_name.clone());
    let deserialize_time_range = timestamp_ty.map(|t| deserialize_time_range(&t));

    let load = self::load::generate(&packed_name, &table_name, &load_checks, &load_where, &load_params);
    let delete = self::delete::generate(&packed_name, &table_name, &load_checks, &load_where, &load_params);
    let decompress = self::decompress::generate(&model, &timestamp, &group_by, float_round, &table_name, using_chrono);
    let store_and_store_grouped = self::store::generate(&model, &timestamp, &group_by, float_round, &table_name, using_chrono);

    quote! {
        use serde::Deserialize as _;

        #item

        #[doc=concat!(" Generated by pco_store to store and load compressed versions of [", stringify!(#name), "]")]
        pub struct #packed_name {
            #packed_fields
        }

        impl #packed_name {
            #load

            #delete

            #decompress

            #store_and_store_grouped
        }

        #filter
        #fields
        #deserialize_time_range
    }
    .into()
}
