on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - beta
          # - nightly

    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup component add rustfmt
      - uses: Swatinem/rust-cache@27b8ea9368cf428f0bfe41b0876b1a7e809d9844
      - run: cargo fmt --all -- --check
      - run: cargo install cargo-expand
      - run: cargo test --workspace
      - run: cargo build --benches
